### ISSUE TITLE
[FEAT]: Additional Data Connectors for structured databases

### ISSUE THREAD

**Issue by viper33802** [Mintplex-Labs/anything-llm#1099]
### What would you like to see?

Additional data connectors to connect to structured databases including SQLite, MySQL, and Microsoft SQL. This could allow for separate workspaces dedicated to structured data retrieval. Also would need to ability to train questions / SQL query in vector DB. Similar approach to Vanna.AI project.

**Comment by timothycarambat** [comment]
This will be accomplished via `agents` in a future version as a plugin/skill because the complexity to add this as a data connector like other "document" based information. In any implementation, there is some need for an "SQL agent" to run relevant queries that can fetch the data and then you opt to embed it. 👍

**Comment by timothycarambat** [comment]
moving to #1298
