### ISSUE TITLE
[BUG]: failing to add multiple documents at the same time.

### ISSUE THREAD

**Issue by XDark187** [Mintplex-Labs/anything-llm#1163]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

uplading more than 5 documents in the embedding tab fails, I have to add them one by one.
if you have a lot of documents it will be a hassle.

### Are there known steps to reproduce?

to reproduce the error simply drag 5 or more documents and drop them in the documents tab and some files will fail to be added.

**Comment by timothycarambat** [comment]
This is because you likely do not have enough resources to be able to embed that many text chunks at the same time - exhausting the CPU resources for the thread. We do what we can to parallelize embeddings but this is ultimately limited by your device's ability to do the work required for that demand. It is possible your device _could_ do it, but also may be artificially throttle by some other kind of process manager.

The alternative is to use an offloaded service to do embeddings locally or on a cloud. (Ollama, OpenAi, etc) or upload the documents one-by-one to ensure the CPU can handle the workload.
