### ISSUE TITLE
[FEAT]: OpenRouter - Fetch from API

### ISSUE THREAD

**Issue by timothycarambat** [Mintplex-Labs/anything-llm#1173]
### What would you like to see?

For OpenRouter we use a statically bundled JSON object to report the models because the JSON is quite large. Given how OpenRouter integrates models very quickly it does not make sense to have this be a chore we have to do every week.

https://openrouter.ai/docs#models

They have a /models endpoint we should leverage.

**Comment by joebitcoinorg** [comment]
How can I edit the config file to  make a selection for an Openrouter llm selection?  

I want to select the new OpenAI o1 versions.   But even with my openrouter api key entered, the dropdown selector won't populate.  Hmmm... maybe since it's so large - I might need to let it sit there for several minutes.
