### ISSUE TITLE
[Question] Beginner help

### ISSUE THREAD

**Issue by janick2024** [Mintplex-Labs/anything-llm#1174]
### What would you like to see?

I used AnythingLLM to upload a file and filled out the required GitHub repository information as instructed, but it was still unsuccessful. Now I'm not sure what to do. More detailed guidance would be helpful; it would be very practical for beginners like me.

**Comment by timothycarambat** [comment]
I dont understand what the issue is here. When you say you uploaded a file, I presume you mean like a text file or PDF to a workspace. Then you mention a Github repository. What did you want to embed ideally?

When you say there was an error, which error specifically and what action did you take that resulted in the error.
