### ISSUE TITLE
[FEAT]: Citation in pinned document

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1277]
### What would you like to see?

Instead of the citation showing first page of the pinned document and stating "continued on in source...", having ALLM note which retrieved vectors are corresponding to pinned documents and while not providing those vectors with the prompt, showing these vectors as citations.

**Comment by timothycarambat** [comment]
This is not possible because that is not how the model parses the information. When the entire document is in context it is not possible for us to highlight exactly where the response came from because the entire result was used. With vector db search we know exactly where the result came from because we provided it, so there is no guesswork

**Comment by RahSwe** [comment]
Maybe I am misunderstanding, but would it not be possible to include the document in the DB search and add the retrieved vector in citations, even though the document in its entirety was forwarded in the prompt, to clarify where there are information in the pinned document relating to the search? That would ease the verification procedure.
