### ISSUE TITLE
[BUG]: Unable to set different Agent Configs in each workspace

### ISSUE THREAD

**Issue by giovanniscalar** [Mintplex-Labs/anything-llm#1303]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When you change the skills in Agent Configuration on a specific Workspace the new configs are reflected in all workspaces.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/149009837/352ecc7f-f80a-46f1-960a-4e8906c2e8a6)

**Comment by timothycarambat** [comment]
<img width="609" alt="Screenshot 2024-05-07 at 4 02 12 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/e00ff0f6-ca42-4537-8651-9382149b660b">

Not _currently_ a bug, this is intentional for the current state of agents. It of course makes sense to have each workspace have different skills, but that is not live yet but is eventually going to be the state of things!

**Comment by giovanniscalar** [comment]
In this case I can create a new issue to address this feature suggestion unless there is already one. Are there any related issues?

**Comment by timothycarambat** [comment]
There is no need to create an issue, it is something we are the core team already expect to be doing. It just makes sense to have it work that way in the future 👍
