### ISSUE TITLE
[FEAT]:  Creating and using specific threads from a workspace via API

### ISSUE THREAD

**Issue by matheus-mondaini** [Mintplex-Labs/anything-llm#1325]
### What would you like to see?

In my case and similar cases, many people have to use the same Workspace to be able to chat with documents from their common space. However, each one needs to have its own message history (their own thread) that will also be used in the context of AI. So, I'd like to know if it would be possible to have a feature allowing the creation of a Thread via API with a unique ID and using it to access the specific thread from a workspace in common.

**Comment by timothycarambat** [comment]
The multi-user version of Anythingllm (Docker version) supports this already. Threads are unique per-user and will not be visible by others on the same workspace.

The thread API however is not accessible via the external API because it requires a user. You just want to get the messages for a unique thread in a workspace?
