### ISSUE TITLE
[BUG]: docker anythingllm failed to create workspace:ubdefined 

### ISSUE THREAD

**Issue by DengxiaoHong999** [Mintplex-Labs/anything-llm#1385]
### How are you running AnythingLLM?

Docker (local)

### What happened?

after get started when ceate your first workspace,i created a workspace named test and response "failed to create workspace:undefined"

**Comment by chalitguza** [comment]
Found the same problem, waiting for a fix.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/2c094c03-07ea-4451-96a8-ec0928ba95d8)

**Comment by jbesclapez** [comment]
Me too!

**Comment by timothycarambat** [comment]
This was fixed in 790fd58b9704af16aee7ed959e0b1cf1b66a514f
The issue was if you:
- Onboarded
- Said "set up for team"
- Set username/pass -> Auth would fail but flow would continue, resulting in undefined error due to permissions on creating workspace.

If you set up the app unauthenticated and then later changed to multi-user this would not occur.
