### ISSUE TITLE
[BUG]: Python processing API is not online. Document short_hamilton_clip.mp4 will not be processed automatically

### ISSUE THREAD

**Issue by xiyuanba** [Mintplex-Labs/anything-llm#1397]
### How are you running AnythingLLM?

Docker (local)

### What happened?

when I upload a file .mp4 with api 
curl --location 'http://192.168.3.186:3001/api/v1/document/upload' \
--header 'Authorization: Bearer AYF7MNM-F8S4RK3-HRC1J4V-WPD73FF' \
--form 'file=@"/home/kiddyt00/PycharmProjects/face_recognition/examples/short_hamilton_clip.mp4"'
response with error 
{
    "success": false,
    "error": "Python processing API is not online. Document short_hamilton_clip.mp4 will not be processed automatically."
}
what this message mean?
and how to slove the promble with mp4 file upload

**Comment by timothycarambat** [comment]
You are using a version of AnythingLLM that is so old we no longer support that. We have not had a python-based document processor now for over 6 months now. 

However that error is exactly what it describes, the collector is offline because it either crashed and exited or never started. Typically a docker restart solves this, also logs from the docker container would help debug further
