### ISSUE TITLE
Save and Embed: onnxruntime_binding.node: The specified module could not be found.

### ISSUE THREAD

**Issue by yongshengma** [Mintplex-Labs/anything-llm#1416]
Hello,

I downloaded "AnythingLLMDesktop" for Win 10 and installed. I got an error after clicking "Save and Embed" button as below.

````
Error: 4 documents failed to add.

The specified module could not be found.
\\?\C:\Users\bill\AppData\Local\Programs\anythingllm-desktop\resources\backend\node_modules\onnxruntime-node\bin\napi-v3\win32\x64\onnxruntime_binding.node
````

I'm pretty sure the onnxruntime_binding.node exists in the path.  I also tried to launch AnythingLLM with administrator privillege but still got the same issue.

Any idea please?

Sincerely,
Yongsheng

**Comment by yongshengma** [comment]
sorry. my mistake. node js not installed.

**Comment by laoheige** [comment]
please ,wo got the same issue .I want know how to slave it .  install node.js app?

**Comment by sfromherz** [comment]
I have the same problem. Is there a solution?

**Comment by timothycarambat** [comment]
Nobody has provided any screenshots, system specs, or even how AnythingLLM is being run in which to replicate or at least help debug this issue.
Logs would help too https://docs.anythingllm.com/installation-desktop/debug

If you have an issue fill out a new issue with a template. Just stating you have the same issue does not help us trace or identify the root cause of an issue so it makes it very hard to help someone
