### ISSUE TITLE
[FEAT]: Generic OpenAI-compatible TTS provider

### ISSUE THREAD

**Issue by babybirdprd** [Mintplex-Labs/anything-llm#1453]
### What would you like to see?

I would like the option to set the baseurl for the tts when using openai as a tts provider

**Comment by timothycarambat** [comment]
Id like to ask what other providers you would like to use that have the same format for TTS as openai? The reason I would be reluctant to support without testing at least one other provider via a generic connection is because I am pretty sure the response blob would be different, resulting in the TTS response not being able to be saved/streamed

**Comment by neubsi** [comment]
I would like this as well, here is a project cloning the openai api: https://github.com/matatonic/openedai-speech
Already working in open-webui, using a Url field for the endpoint.
thx
