### ISSUE TITLE
[FEAT]: Add option to have LLM rephrase user question before querying vector store

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1455]
### What would you like to see?

When an LLM rephrases a user’s question, it often leads to better vector matches. Please add a setting to make this an option, including a prompt template. I guess maybe it’d be good to search by BOTH the user’s initial request AND the LLM’s rephrased question. This would be relatively easy to put in, but it might slow down initial response time for some, if only slightly. 

Can you do the same with hallucination detection and mitigation. Again. User would encounter a perceived performance hit if they weren’t aware of what was going on underneath.

Would be a trade off of performance and utility.

**Comment by timothycarambat** [comment]
There are far faster ways to improve retrieval and accuracy over doing this. You would be surprised, but doing this would be quite high latency and result in minimal gains. Eventually, what ends up happening is you have re-built a Reranking model (https://github.com/Mintplex-Labs/anything-llm/issues/1124) because that is what those solve and is the logical conclusion of following this path!

Improvements we will add that can be done far prior to resorting to this:
- Include sources from previous chats in history
- Knowledge Graphs (https://github.com/Mintplex-Labs/anything-llm/tree/knowledge-graph-support)
- Reranker support

**Comment by atljoseph** [comment]
All behind what you mentioned!
