### ISSUE TITLE
[FEAT]: Refreshable data sources, and question about exact method of html data vectorization. 

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1458]
### What would you like to see?

Be able to input a GitHub repo and GitHub pat token and have the software remember that and be able to let the user go and click refresh on it to automatically replace and reindex it. Confluence and YouTube transcripts too, along with NOT having to copy paste creds in each time. That is really cumbersome. It’s also cumbersome to have to ALWAYS re-input the files to be ignored. 

Might be hard to do with files. I get that. But refresh would be a huge value add. 

Lastly, I notice that webpages indexed are stored as html. Do they get indexed that way? Wouldn’t it be better to turn to pdf (headless chrome) and then read it, or read it with reader mode, and then have LLM summarize?

**Comment by timothycarambat** [comment]
> Lastly, I notice that webpages indexed are stored as html. Do they get indexed that way? Wouldn’t it be better to turn to pdf (headless chrome) and then read it, or read it with reader mode, and then have LLM summarize?

No, this would not be better because there is no reliable way to truly turn HTML into a PDF that does not result in a massive loss of data. When we pull in HTML we pull in the text only, not the tags plus text since a lot of that data is not useful as content anyway. Going from HTML -> PDF -> Text is duplicative because you can go from HTML -> Text with less loss.

Live file import is being handled in https://github.com/Mintplex-Labs/anything-llm/issues/1129

**Comment by atljoseph** [comment]
Ok. I’m not sure this needs closing. The primary ask is refreshability.

**Comment by timothycarambat** [comment]
Refreshing is the same concept as live-sync: https://github.com/Mintplex-Labs/anything-llm/issues/1129

Fundamentally both require the same specifications

**Comment by atljoseph** [comment]
Perfect thanks
