### ISSUE TITLE
[BUG]: Non AVX CPU core dumps.

### ISSUE THREAD

**Issue by Dozer316** [Mintplex-Labs/anything-llm#1470]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Hi there,

The latest docker pull for anythingllm on a CPU with AVX (No AVX2) seems to result in a core dump when a search is performed after which the container shuts down.   Running the same built image on a CPU with AVX2 support doesn't exhibit the same behaviour.
![llm-1](https://github.com/Mintplex-Labs/anything-llm/assets/42313740/ca29ef7a-5e38-4256-90e5-8cdf6f4b0b04)

I'm not sure which part of the stack is core dumping but the container logs shows.
[NativeEmbedder] Initialized
[NativeEmbedder] Initialized
[Event Logged] - update_embedding_engine
/usr/local/bin/docker-entrypoint.sh: line 7:   107 Illegal instruction     (core dumped) node /app/server/index.js

If something is being compiled with the AVX2 flag enabled, would it be possible to provide a workaround for this on older CPUs with AVX support only?

Cheers.

**Comment by timothycarambat** [comment]
This is related to https://github.com/Mintplex-Labs/anything-llm/issues/1331#issuecomment-2122238892

In fact, you just confirmed that hypothesis. The issue is that the underlying libraries do not support running ONNX on AVX arch CPUs. If you swap to another embedder model then you will not have this issue as you will not attempt to run anything via the ONNX runtime, which apparently does not support AVX?

**Comment by MrTAZ42** [comment]
Hi,
Anyone try to set OMP_NUM_THREADS=1 ?

**Comment by nikita2206** [comment]
Was having similar issues with AnythingLLM in the docker container. Even with OpenAI embedder configured. I wasn't sure if AnythingLLM was maybe still using native embedder, but it looks like the issue might be in the vector database that is shipped together with AnythingLLM in the docker image (LanceDB); quick googling also suggests that it uses AVX.
