### ISSUE TITLE
[BUG]: Getting errors on startup 

### ISSUE THREAD

**Issue by ivanenev** [Mintplex-Labs/anything-llm#1478]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[22883:0521/233124.387191:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
[22883:0521/233124.669827:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
glx: failed to create dri3 screen
failed to load driver: nouveau
glx: failed to create dri3 screen
failed to load driver: nouveau
prisma:warn Prisma doesn't know which engines to download for the Linux distro "artix". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "artix". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:/home/mts/.config/anythingllm-desktop/storage/anythingllm.db"

Error: Schema engine exited. Error: Could not find schema-engine binary. Searched in:
- /tmp/.mount_AnythiDCKQSH/resources/backend/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x
- /tmp/.mount_AnythiDCKQSH/resources/backend/node_modules/prisma/schema-engine-debian-openssl-1.1.x
- /tmp/.mount_AnythiDCKQSH/resources/backend/node_modules/schema-engine-debian-openssl-1.1.x
- /tmp/.mount_AnythiDCKQSH/resources/backend/node_modules/prisma/runtime/schema-engine-debian-openssl-1.1.x
prisma:warn Prisma doesn't know which engines to download for the Linux distro "artix". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Prisma schema loaded from prisma/schema.prisma
prisma:warn Prisma doesn't know which engines to download for the Linux distro "artix". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Error: 
EROFS: read-only file system, unlink '/tmp/.mount_AnythiDCKQSH/resources/backend/node_modules/.prisma/client/index.js'

**Comment by timothycarambat** [comment]
You are using an unsupported `xdg-desktop` app to show the UI for your linux distro and will not work with our AppImage
Reddit: https://www.reddit.com/r/hyprland/comments/14bpjuy/no_such_interface_orgfreedesktopportalfilechooser/

Additionally: 
> prisma:warn Prisma doesn't know which engines to download for the Linux distro "artix". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Prisma schema loaded from prisma/schema.prisma
prisma:warn Prisma doesn't know which engines to download for the Linux distro "artix". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Error:
EROFS: read-only file system, unlink '/tmp/.mount_AnythiDCKQSH/resources/backend/node_modules/.prisma/client/index.js'


Indicates you will have the exact same issue after you solve the desktop issue as the pinned issue https://github.com/Mintplex-Labs/anything-llm/issues/898 for which there is a solution, but both of these problems would be fixed by using docker instead of the AppImage
