### ISSUE TITLE
[DOCS]: How to use @agent in API mode ? 

### ISSUE THREAD

**Issue by OxaD** [Mintplex-Labs/anything-llm#1484]
### Description

Hi,

Maybe its's already in the documentation, or as an upcoming feature. But I couldn't find a way to use @agent through the API. I love AnythingLLM especially because of the agents. However, I don't know how to get results from a web search using the API for instance. Or other example, when asking the AI to look in a specific document (which works in agent mode).

Many thanks.

**Comment by timothycarambat** [comment]
The `@agent` directive is not available in the API because there is no way to halt the worker since there is no "Stop generation" via the API. To prevent runaway agents, which can occur with Opensource models, we dont have agents in the API yet.

They would be able to be used via a separate endpoint or body parameter so we can be sure you have the controls needed to prevent any kind of agent runaways!
