### ISSUE TITLE
[FEAT]:  A way to see agent work being done in each workspace

### ISSUE THREAD

**Issue by dctmfoo** [Mintplex-Labs/anything-llm#1506]
### What would you like to see?

If you look at the below two screenshots, one has given an extensive log on what the agent has done and the other has none. Provide a way to turn on/off what the agent is doing in the background. THanks
![image](https://github.com/Mintplex-Labs/anything-llm/assets/128729140/4e883f19-064f-4b47-bb14-823d27279af1)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/128729140/49aeeb7e-a115-440f-9d44-ac2ed5976618)

**Comment by timothycarambat** [comment]
Its extremely important that you can see everything the agent is doing at all times to prevent runaway recursive tool calls which can occur with any LLM, even cloud based ones. We add internal limiting to prevent this, but it can still happen with some functions and in lieu of showing an empty screen since streaming is not enabled, we show this thought chain.


In the first screenshot nothing was called or dont by the agent. It just either made something up directly or inferred it from previous chat history
