### ISSUE TITLE
[FEAT]: Add alternative Gemini model API reference

### ISSUE THREAD

**Issue by RahSwe** [Mintplex-Labs/anything-llm#1535]
### What would you like to see?

An additional option when choosing Gemini version, pointing to the latest stable version (API "gemini-1.5-pro")

<img width="789" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/163884933/127eccd1-32fa-4b93-9acd-c6a6e86744c9">

**Comment by timothycarambat** [comment]
@shatfield4 before doing this, please check if Google finally added a `/models` endpoint so we stop having to do these chore tasks as they update their model list randomly.

**Comment by shatfield4** [comment]
Unfortunately the only way to be able to call the models endpoint from google is to setup a Vertex project with OAuth and enabling certain scopes to be able to list all models. This is not feasible since it would require a user to set this up themselves and cannot be accessed with just a gemini API key.

[Docs for REST API models list endpoint](https://ai.google.dev/api/rest/v1/models/list) 

I also found this issue on the npm package used for accessing the gemini API and it seems like it has gone stale and has not been worked on for months [Link to issue](https://github.com/google-gemini/generative-ai-js/issues/54)
