### ISSUE TITLE
[FEAT]: Support ingesting docusaurus documents on anything-llm collector

### ISSUE THREAD

**Issue by OrcVole** [Mintplex-Labs/anything-llm#1539]
### What would you like to see?

AnythingLLM collector has options for e.g. github books, youtube (for transcripts). Please add ingest of docusaurus type documentation as an option.

https://docusaurus.io/

**Comment by timothycarambat** [comment]
This would be more easily accomplished via the Github connector pointing at the GitHub repo using Docusarus or uploading the  markdown files directly _or_ using the bulk link scraper since all of thee would amount to the same out without a need for a custom built integration that would likely just call one of these built-in functionalities for you since there is no specific structure or API required for Docusarus sites
