### ISSUE TITLE
[BUG]: Agent not working

### ISSUE THREAD

**Issue by mariusmutu** [Mintplex-Labs/anything-llm#1548]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When I call the @agent there is an error: "No provider found to power agent cluster."

I tried with both Ollama and OpenAI. The chat works, but not the @agent

![2024-05-27-001](https://github.com/Mintplex-Labs/anything-llm/assets/6256011/e406349f-820d-4f80-8c8e-558a1439812d)

**Comment by timothycarambat** [comment]
Open workspace settings > Agent Configurations > set the LLM you want to use for agents. We dont assume its the same as the workspace because agents are not 100% covered yet  **and** not all agents are good at tool calling so we provide the ability to use agents with another model and chat with a different one in the same workspace

**Comment by ldl1949** [comment]
I got the same error. Any solutions?
