### ISSUE TITLE
[BUG]: Agent button "@" disappears after one use in prompt window

### ISSUE THREAD

**Issue by AIbottesting** [Mintplex-Labs/anything-llm#1554]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Agent button "@" disappears after one use of agent in prompt window. To get it back I have to click out of the thread and back into original thread. I am running the latest version Windows 10 64bit, and Google web search API, and LM Studio as agent which is running Llama-3-Instruct (the model for the work space is "system default" and the system is also from the same LM Studio Llama-3 instance). AnthingLLM v1.5.5

### Are there known steps to reproduce?

To reproduce just use the agent for Google web search

**Comment by frost19k** [comment]
That's because the agent mode is active. When you don't see the `@` button every prompt is routed to the agent until you exit the agent mode with `/exit`

**Comment by timothycarambat** [comment]
@frost19k is correct. The reason it is gone is because an `@agent` session has activated and now all chats will be with an agent until the sessions ends or is `/exit`ed. This is shown in the text once the session starts.

**Comment by timothycarambat** [comment]
@AIbottesting no worries, not a waste of time at all. I need to improve documentation all over so these kinds of things can be found on docs.useanything.com anyway

**Comment by frost19k** [comment]
@timothycarambat When you do update the documents, it would be swell if you recommended 2 or 3 huggingface models that do work well with function calling - because currently (at least for me) it's 😮‍💨

![Screenshot from 2024-05-29 10-46-21](https://github.com/Mintplex-Labs/anything-llm/assets/49780407/494dfa7a-271c-4cff-bc57-1025947b1f0c)

Note: I've tried agents with both Google Search and Serper, but that's irrelevant cause the thing's calling `web-scraping` for some reason. It's a mistral model.

**Comment by penjud** [comment]
> it would be swell if you recommended 2 or 3 huggingface models that do work well with function calling

Given that the models change so frequently, and newer/better versions appear so quickly we are better looking for models that fit our own specifications, and ensure the model is tuned for 'tools'.
