### ISSUE TITLE
[BUG]: Threads inside Workgroups get locked up

### ISSUE THREAD

**Issue by AIbottesting** [Mintplex-Labs/anything-llm#1555]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When I give a big task to the LLM (and probably exceeds the context window) the threads seem to lock up within the workgroup with a big "X" next to each one. I have my context window set a 4096 on LM Studio. If I want to select another thread in the same workgroup I cannot. I am forced to select another workgroup and back again to unlock the threads. I am using Windows 10 64bit latest. AnthingLLM v1.5.5

### Are there known steps to reproduce?

I am guessing you have to exceed the context window
![Screenshot 2024-05-28 061042](https://github.com/Mintplex-Labs/anything-llm/assets/124838865/d3ac16aa-9859-42f4-9609-3a81553d0454)

**Comment by timothycarambat** [comment]
The threads having an "X" next to them is from tapping `Control` or `CMD` - it toggles the bulk deletion option, will will be changed to "press-to-hold" (changed in https://github.com/Mintplex-Labs/anything-llm/issues/1513).

The reason that it is "locked up" is not AnythingLLM, it is because LMStudio's server does sequential processing and cannot parallel process incoming chats - so it seems to be locked up, but its actually queued in the LM Studio server
