### ISSUE TITLE
[BUG]: Can't load local documents or fetch website

### ISSUE THREAD

**Issue by devdanke** [Mintplex-Labs/anything-llm#1589]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Can't load documents or fetch websites.
<img width="376" alt="Screenshot 2024-06-01 at 1 21 55 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/15268897/e4ec1504-4ab2-459e-938d-6e89a7eec6fa">
<img width="334" alt="Screenshot 2024-06-01 at 1 22 50 AM" src="https://github.com/Mintplex-Labs/anything-llm/assets/15268897/774ea910-4140-47bf-bf80-2f875db52b20">

### Are there known steps to reproduce?

1. Download AnythingLLMDesktop-Silicon.dmg v1.5.5 from your website, for my MacBook Pro M2 Pro.
3. Install as per instructions in Applications folder.
4. Run Anything LLM.  
5. Choose Ollama as LLM and dolphin-llama3 as model.
6. Leave unchanged AnythingLLMEmbedder & LanceDB default choices.
7. Create workspace.
8. Click "upload a document" link, which shows Documents screen.
9. See the notice that Document processor is offline (attached image).
10. Dragging local documents has no effect.
11. Try to fetch a website.
12. Error message about Python processing API. (attached image)

**Comment by devdanke** [comment]
Ran it from .../AnythingLLM.app/Content/MacOS with `open -a AnythingLLM`.  It started.  But nothing logged to console when I triggered a *Fetch website* error.

**Comment by timothycarambat** [comment]
Wow, we need to change that error message. Regardless, the issue comes from the `Document collector` being offline totally.

When you start the anythingLLM app it should spawn a process for purely document collecting. This happens on boot and if the default port of 8888 is occupied it will hunt for another port - however, we have seen times where someone is running something on 8888 and then the app boots and because these is a PID for 8888 the app assumes it booted. Then when we try to interact with that process, it isnt what we expect and get an error like above.

Can you check if you have any process running on 8888 currently? This typically is a development flask sever for more people.

Otherwise, [run the app in debug mode to get the logs on startup](https://docs.useanything.com/debug)

**Comment by devdanke** [comment]
When AnythingLLM is running:
`~> sudo lsof -nP -i4TCP:8888 | grep LISTEN`
returns:
`AnythingL 4589   me   29u  IPv6 0x159babc9c54f3f03      0t0  TCP *:8888 (LISTEN)`

When AnythingLLM is not running, that `lsof` command returns nothing.

---

When I manually start AnythingLLM from its `.../Content/sMacOS`, it's stdout has:
`[production] AnythingLLM Standalone Document processor listening on port 8888`

When I trigger the *Fetch website* error, AnythingLLM does not write anything to stdout or stderr.
