### ISSUE TITLE
[BUG]:  LanceDBError: No vector column found to create index

### ISSUE THREAD

**Issue by crypto-maniac** [Mintplex-Labs/anything-llm#1695]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hello, i have installed AnythingLLM Destop app for my macbook pro montery, after download the LLama 2,3 etc,,
i have created a workspace and was able to chat (its low speed on my mac) but when i add a document and send them to the workspace, i try to chat again to talk about my document and i got the error

LanceDBError: No vector column found to create index

thanks you very much for the help

**Comment by timothycarambat** [comment]
This error occurs when you have changed the embedder model after previously upload a document to a workspace that was embedder with some previous model.

In either case, Open the workspace's settings and go to "Vector Database" and click "reset vector database" and you should be able to both embed documents and send responses.

This issues occurs when you change the embedder because your embedded prompt dimensions and the vector database vector column have different dimensions.
