### ISSUE TITLE
Translate User Query as 1st step

### ISSUE THREAD

**Issue by khalilxg** [Mintplex-Labs/anything-llm#1699]
### What would you like to see?

Goal: translate user query to the language of documents.

How: preprocess user query to be translated before sending it to indexsearch

**Comment by timothycarambat** [comment]
This is not something we wouldnt plan to explicitly support since it seems to really be a use-case specific. This could also be then applied to pre-translating documents prior to embedding. In either case, the use-case of AnythingLLM in whatever workflow you can handle this on the client side by:

- Writing your prompts in the given language
- Translating documents to the intended language that it will be prompted in prior to upload so the embeddings are not off.
- Leverage a capable multi-lingual embedding model that can tokenized both languages efficiently without much semantic loss

**Comment by khalilxg** [comment]
Thank youu !
