### ISSUE TITLE
[FEAT]: multiple chatbots

### ISSUE THREAD

**Issue by chalitbkb** [Mintplex-Labs/anything-llm#1702]
### What would you like to see?

It would be fantastic if the "AnythingLLM" workspace could support live chat through multiple provider Model APIs simultaneously.

Additionally, enabling chats across several workspaces at the same time would be beneficial. Instead of being limited to chatting within a single workspace, this feature would allow interaction with different workspaces that might use varying model APIs and system prompts but share similar approaches. This simultaneous chatting capability would save time by reducing the need to switch between workspaces. Sometimes, I'm not satisfied with the responses from one workspace and would like to try another.

![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/58bffc4f-befe-4628-b525-9efe076df2d3)

![image](https://github.com/Mintplex-Labs/anything-llm/assets/32437546/13fb3242-a16d-48bc-875b-a8e391666a46)

**Comment by PGTBoos** [comment]
I think for this idea, (i did those things directly in python in the past).
There should be various discussion types and settings

- What's the role of a participant, may it act as a discussion leader ? (keeping it on topic, and asking other experts)
- Can an agent talk to any other agent, or is there a strict follow up pattern, ea next agent = "agent name"
- Group chat, bots, all writing on the same output screen, 
  - Will there be an agent, or agentless, single output file (so to keep the chatter out of the doc).
  - output may also be perhaps not a file but a custom api endpoint (blog) /and maybe input as well (ea some news article)
- Should a discussion cycle wait for human input, or can agents continue themselves.
- Should an agent be able to adjust the past history chat to summarize  / or to steer topic back
- Should agents be able to be turned on / off on a per need basis (to reduce memory and chat participation).
- Should agents have access read write to some kind of a simple value store, on which end users can apply some python.
  ea current time, current mood as a string, ... etc
- Should there be a generic prepompt database to quickly config llm chat participants  


Maybe i dive a bit to deep here, but since i did this in python so i share some ideas here.
the list probably can be made longer.
