### ISSUE TITLE
NPM `openai` and `@langchain/openai` vs. Azure OpenAI?

### ISSUE THREAD

**Issue by ericthomas1** [Mintplex-Labs/anything-llm#1707]
Hello,

The `server/package.json` file lists `openai`, `@langchain/openai` and `openai` as dependencies of Anything LLM.

Are **all** of these required when using Azure OpenAI or will `@azure/openai` suffice?

Thank you

**Comment by timothycarambat** [comment]
If using Azure you need `@azure/openai` because their library is vastly different from the regular OpenAI one. The langchain import is a wrapper for OpenAI to normalize its interface for other providers.

Can I ask what you are doing since this is the ~third issue of this type you have opened?? These types of questions would be better on discord than Github issues since it sounds very specific to what you are trying to accomplish?

**Comment by ericthomas1** [comment]
I would have totally joined the Discord and posed these questions but my org doesn't allow it. You've been a great help in answering and I will not abuse the GitHub Issues. Thanks again.

**Comment by timothycarambat** [comment]
@ericthomas1 Ah, understood 👍
