### ISSUE TITLE
[CHORE] How user feedback works?

### ISSUE THREAD

**Issue by timwu-ipevo** [Mintplex-Labs/anything-llm#1749]
Well, this is not an issue.  It's just my personal question about Anything's internal design.

AnythingLLM's user feedback feature is a valuable addition to its functionality. I've been investigating how it operates, tracing it down to the model layer. However, I only found that it saves feedback into a field called 'feedbackScore'. I'm curious about how this feedback actually influences the response generation process. Could someone provide more insight into how this mechanism works and affects the formation of responses?

**Comment by timothycarambat** [comment]
Ah, that marker/flag has no impact on the ranking, scoring, or order of chats in a thread or any impact at all. It is simply a flag that shows up once you export chats so that you can pre-filter or review them.

Some people encourage use of that feedback button so that when they export they can easily prune all bad responses and then append the good results to some dataset they then use for a fine-tune job.
