### ISSUE TITLE
[BUG]: Cannot read properties of undefined

### ISSUE THREAD

**Issue by rosano** [Mintplex-Labs/anything-llm#1753]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I sent a message in a new workspace after configuring to use the only installed model: codellama 7b from provider AnythingLLM.
<img width="494" alt="Screen Shot 2024-06-24 at 11 41 07" src="https://github.com/Mintplex-Labs/anything-llm/assets/1680612/7781602e-f809-48fb-a7f4-68ca30fd1120">

**Comment by timothycarambat** [comment]
This seems to be that the vectorDB was not saved. Nobody else has had this issue on the desktop app and we haven't pushed a new version. When you go to "Vector Database Preference" you have LanceDB selected?

**Comment by rosano** [comment]
I'm using macOS 10.14 Mojave.

**Comment by timothycarambat** [comment]
@rosano  are you on an M1? Seems like you downloaded the Intel version and not the Silicon version of the app  (or vice versa). It is was expecting to find `darwin-x64` that is for Intel chips, not M1. IIRC you _might_ be able to run AnythingLLM in compatibility mode by downloading the wrong version but the binaries we use for some libraries wont exist and you will get issues like this.

**Comment by rosano** [comment]
@timothycarambat Thanks for the feedback. I have an Intel mac and downloaded `AnythingLLMDesktop.dmg` which should be the correct version. I wonder if my system is too old but there aren't specific requirements on either of these pages:
- https://docs.useanything.com/installation/system-requirements
- https://docs.useanything.com/installation/desktop/macos

**Comment by timothycarambat** [comment]
How old is your machine? LanceDBs only real requirement is AVX2 instruction set on the chip

**Comment by rosano** [comment]
> How old is your machine? LanceDBs only real requirement is AVX2 instruction set support on the CPU

@timothycarambat It's a 2012 MacBook Pro Retina. How might I figure out whether it has that requirement?

**Comment by timothycarambat** [comment]
@rosano The processor in the 2012 MBP is [an Intel i7-3520M](https://www.intel.com/content/www/us/en/products/sku/64893/intel-core-i73520m-processor-4m-cache-up-to-3-60-ghz/specifications.html) - scrolling to Instruction set I see

Instruction Set Extensions:  Intel® AVX

So I am fairly confident the app just cannot support the AVX2-based instruction. As a workaround, you will have to use any other vector database provider. This is obviously not ideal as it requires additional setup on your end, but that is a limitation imposed by the default VectorDB provider we use. AVX2 is not really a "new" tech and has been around for over a decade, which is why we have not seen this issue reported in the desktop client before and the speed gains using AVX2 support is very large :/
