### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by dgarner-cg** [Mintplex-Labs/anything-llm#1767]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

LLM Download freezes on Windows, will not resume - starts back at 0%..
Restarting application or even computer will not help files resuming download ... Have been trying to download Dolphin-Mixtral for 2 weeks now.

**Comment by timothycarambat** [comment]
> 2 weeks

That is definitely not a reasonable time for a download, however since it does show a % that indicates that it is attempting to communicate or reach Ollamas model server. Are you on a VPN? Others have reported issues downloading models from Ollama (using our built-in or otherwise) when on a VPN or behind a corporate firewall.

I can say this "bug" is network related and on your end and not within the app iteself.

**Comment by timothycarambat** [comment]
Yes! If you have access to an existing Ollama models folder you can copy the `blobs` and `manifests` folder into
Windows: C:\Users\user\AppData\Roaming\anythingllm-desktop\storage\models\ollama`
Mac: /Library/Application Support/anythingllm-desktop/storage/models\ollama`

To stop the existing download you can swap to any other LLM and save it and then swap back. Also if you have Ollama already you can just connect directly to your Ollama running on your machine and avoid all of the above
