### ISSUE TITLE
[FEAT]: multiple data connectors

### ISSUE THREAD

**Issue by flefevre** [Mintplex-Labs/anything-llm#1774]
### What would you like to see?

it could be great to have additional data connector such as:

- mysql
- postgresql
- sharepoint
- network folder on the same machine

**Comment by timothycarambat** [comment]
> network folder on the same machine
You can just drag and drop these documents over. We for sure wont support this due to permission issues

> sharepoint
This will be covered by Enterprise connectors or plugins because we find building each plugin per-use-case is really cumbersome since most go unused

> mysql/pg
This is better covered by the `@agent` SQL connector. Data connectors are for pulling in static data to be embed and vector-search. Tabular data is _very bad_ for most vector RAG applications and it wouldn't be wise to copy the whole DB into a vector db!

**Comment by bookcaseballpen** [comment]
pgvector seemingly is getting much better than many vector only database now.
