### ISSUE TITLE
Why am I using Agent to access GPT3.5 instead of my local model[BUG]: 

### ISSUE THREAD

**Issue by Linjiahua** [Mintplex-Labs/anything-llm#1840]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/23415587/a70355af-d901-42db-a64b-4df6813b943b)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/23415587/9441f77a-07aa-4a24-9683-b26c24c52eba)
![image](https://github.com/Mintplex-Labs/anything-llm/assets/23415587/cf34e9a5-c5e4-413a-bdcc-2361d44cd00c)

**Comment by timothycarambat** [comment]
Because you either have no model set in the system-settings for the "Generic OpenAI Provider" so we just use that tag as a fallback. In LLM Preference select Generic OpenAI and set/define the model you want to use and click save. Then you can swap the system model back to whatever it was prior and continue to use it for agents.

**Comment by timothycarambat** [comment]
@shatfield4 I think for here https://github.com/Mintplex-Labs/anything-llm/blob/e952182de029a1bbcdaa54bb2f13c27f15edd021/server/utils/agents/index.js#L188-L189 the issue is providers without a named chat model will always use the last-known workspace agentModel settings and then fallback to the default.

We should not access this.invocation.workspace.agentModel if the model has no defined model per-workspace and no reliable fallback

**Comment by Linjiahua** [comment]
@shatfield4 @timothycarambat Thank you very much for your work
