### ISSUE TITLE
[BUG]:  In Query mode, it will utilize a LLM to generate answers.

### ISSUE THREAD

**Issue by dkasa** [Mintplex-Labs/anything-llm#1859]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When I use the query mode and ask a question that is not within the search scope of the knowledge base, AnythingLLM responds that it cannot find the answer. 
However, after I ask a question that can be searched and found, the mode changes to chat mode, and for the previous questions that couldn't be found, AnythingLLM starts to use the LLM to provide answers instead of staying in query mode.
 Is this a bug?

**Comment by timothycarambat** [comment]
Since documents/references were previously found in the chat thread _those_ references are used even if the last question sent has no references. It used to work the way you described but that is not longer the case because it limited the user to basically needed to know exactly what existed in the vector db or else they would get a refusal. Even followup questions were refused and it leads to a bad experience

previous state of `query`:
"Tell me about XYZ"
"Sure, here is information with citations..."
"What about Z?"
-> LLM Refuses since the previous prompt has no result.

currenty state of `query`:
"Tell me about XYZ"
"Sure, here is information with citations..."
"What about Z?"
"Sure, here is more about Z i can infer" (using the citations from the first answer)

**Comment by dkasa** [comment]
i see ...
