### ISSUE TITLE
[FEAT] Integrate CrewAI into @agents

### ISSUE THREAD

**Issue by jeffscottward** [Mintplex-Labs/anything-llm#1887]
Tasks, Roles, Tools, etc etc

**Comment by timothycarambat** [comment]
CrewAI is a framework for programming agents in python, not a "product", so its not like we can enable you to "port" an agent from crew into AnythingLLM since their only way to invoke crewAI agents via API is [via their paid offering](https://www.crewai.com/crewaiplus) :(

We are a NodeJS project, so its not like we can port their code directly into our codebase. If the question is "I want to be able to code an agent like i can with crew" then yes of course that would be coming when we do "custom agents" 👍

**Comment by jeffscottward** [comment]
Understood! Thanks for the clarity. :)
It’s actually really great because I’m a JavaScript person really myself.

When you do custom agents, I hope that you integrate Mermaid diagrams or
have some sort of bridge over Obsidian, it being electron/JS based too.

Also… “something something Fabric prompt library”. Thinking if I should
have a Fabric pipeline in obsidian or here.


------------------------------

Jeff Scott Ward
Founder / A.I. & U.I. Engineer
*F0.ai*
------------------------------

**Comment by timothycarambat** [comment]
The current plan/concept we have internally is basically a flowise-like node/graph builder. Not flowise itself obviously since that is quote more elaborate, but a UI like that

**Comment by jeffscottward** [comment]
Very cool!

The main thing I would definitely suggest is having some sore of text
syntax for wiring them together.

A UI would just be a nice to have on top IMO. LLM agents that are rapid
fire talking to each other would need a syntax to reflect, update, auto gen
etc.

Anything where you can have some sort of state machine / diagramming syntax
in just text whether it’s Xstate or Mermaid or Diagram-as-Code (eraser.io)
or DSL etc would be the building block if I was designing the UX of this
(Mermaid my choice, plays well in markdown). Crew has a plan for this
already.

But yea excited to see where this all goes. Thank you for doing all this!




------------------------------

Jeff Scott Ward
Founder / A.I. & U.I. Engineer
*F0.ai*
------------------------------
