### ISSUE TITLE
[BUG]: Missing extra meta data in the API document/raw-text

### ISSUE THREAD

**Issue by byzheng** [Mintplex-Labs/anything-llm#1894]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I am following Anything LLM developer API documentation and using `document/raw-text`. 

This is the data I post 

```
{
  "textContent": "This is the raw text that will be saved as a document in AnythingLLM.",
  "metadata": {
    "title": "title",
    "key": "value"
  }
}
```
A new document with id `99502983-20fa-4cd1-bef5-e17cd0c56dae` is added. 

Then I used `/v1/document/{docName}` to retrieve document with name `raw-title-99502983-20fa-4cd1-bef5-e17cd0c56dae.json`, but cannot find the `key` and `value`

**Comment by timothycarambat** [comment]
This endpoint value is really for upserting simple text, the custom metadata that does not comply to our uniform schema will be omitted - this entire endpoint was really just a simple extension of the endpoint since the API process to upload a document _then_ embed was very clunky and this streamlined that process.

https://github.com/Mintplex-Labs/anything-llm/blob/7b42a67acf9df03cc9ff780beaf43ef4d5bf2e67/collector/processRawText/index.js#L13-L35

So, this behavior is intentional.
