### ISSUE TITLE
[BUG]: Unable to use AzureOpenAI embedder

### ISSUE THREAD

**Issue by ehengtan** [Mintplex-Labs/anything-llm#1906]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Failed to embed using AzureOpenAI embedder. Always returns 'Failed to load resource: the server responded with a status of 504 (Gateway Time-out)'

I tried my key offline and it seems like api_version is a required parameter, and its missing from the settings page. Could that be the reason? 

![py](https://github.com/user-attachments/assets/c080582d-06c2-4f17-ad53-6146536eb21e)
![setting](https://github.com/user-attachments/assets/ed84afd9-d452-43f8-bbef-9fe4c39a633f)

### Are there known steps to reproduce?

Change your embedding provider to AzureOpenAI.
Upload any file and it'll fail.

**Comment by timothycarambat** [comment]
> Upload any file and it'll fail.

When you mean upload, do you mean `embed`? The embedder is not called during file upload, only embedding

**Comment by timothycarambat** [comment]
@ehengtan Okay so i am fairly certain this is due to a bad client configuration - here is my walkthrough that does not replicate the reported bug:

First in the AnythingLLM UI i fill out the endpoint and key, which i acquire from this screen:
<img width="1042" alt="Screenshot 2024-07-22 at 1 14 41 PM" src="https://github.com/user-attachments/assets/d071b950-c0e3-45ac-9c28-1c36eca3244b">


Then in the Azure OpenAI studio I create an embedder model deployment
<img width="620" alt="Screenshot 2024-07-22 at 1 16 13 PM" src="https://github.com/user-attachments/assets/46b37598-a904-4e7d-8f24-5e177408b510">

I put the `text-embedder` label into AnythingLLM.

Embedding documents works successfully.

**Comment by oiao** [comment]
@timothycarambat Same issue here. Azure OpenAI is missing a field and is currently broken. The full request URL should look like this: `${BASE_URL}/openai/deployments/${DEPLOYMENT_ID}/chat/completions?api-version=${API_VERSION}`. Currently, there is no way to provide the `API_VERSION` string in the settings.
