### ISSUE TITLE
[DOCS]: I'm confused at why I need to upload a document?

### ISSUE THREAD

**Issue by easaw** [Mintplex-Labs/anything-llm#1931]
### Description

I have had a look at the docs, and maybe I'm understanding the purpose of this.

I have Ollama running fine and using the localhost version.

Why do I need an internet connection to 'upload' files? Why is document interaction not done locally?

Thank you.

**Comment by timothycarambat** [comment]
You do not need an internet connection to upload a document. This issue does not describe what you are attempting to do, but you can upload, embed and chat with AnythingLLM without an internet connection. Without more details I cannot help debug what exactly you are running into.

**Comment by george-holt** [comment]
@timothycarambat - I had the same question. I'm running a single-user instance is there a way to scan a list of folders for new content? Use case: I use Obsidian for notes. For the most part it's just markdown files. I would love to have anything-llm to scan a list of local directories. 

I think to do this on my own, I would use a file sync tool to copy content into the upload folder... but then I started wondering about file versioning and how multiple versions of a file would get added into the vector database.

Do you have a suggestion on how to best handle this use case with the existing product?

**Comment by timothycarambat** [comment]
@george-holt We have a [beta feature for document sync](https://docs.anythingllm.com/beta-preview/active-features/live-document-sync) and have an open issues [_specifically_ for Obsidan ](https://github.com/Mintplex-Labs/anything-llm/issues/1400) as well (which we will sync too).

When it comes to syncing we _upsert_ new embeddings when a document changes and don't multi-version it so data is not duplicated! 

We are actually going to make the local watcher more robust so you can watch entire directories and sub-files and such - which is why it is in beta. The currently implementation is not very performant so we are going to migrate this to `chokdir` so we can listen to `fs` events native in the system without a large overhead.

**Comment by easaw** [comment]
I know it's a while later, but I'd like to come back to this. I've seen similar issues regarding:

> "Document Processor Unavailable"
"We can't upload your files right now because the document processor is offline. Please try again later."

I assumed 'offline' meant no internet, but perhaps I was wrong. Is there something the processor needs?
I can confirm AnythingLLM can connect to the internet, as while I am running Ollama, before that I allowed it to start downloading one of the models.

I have just installed the latest 1.6.4 on a Apple silicone MBP.

![Screenshot 2024-08-29 at 21 01 55](https://github.com/user-attachments/assets/7f3836a8-41d6-4bd3-8458-19f00fa4fa10)

As you can see I'm unable to 'upload' files.

Thank you.

**Comment by easaw** [comment]
I can confirm this solved the issue:

https://giter.vip/mintplex-labs/anything-llm/issues/866

> Terminal run: `/Users/username/Applications/AnythingLLM.app ` 

However, when I then launch that by clicking the app in ~/Applications, it gives me a warning:

![Screenshot  warning damaged](https://github.com/user-attachments/assets/d6b37911-fde6-4cf6-be2a-eacb42a6f771)
