### ISSUE TITLE
[FEAT]: Multi-model support

### ISSUE THREAD

**Issue by djstrong** [Mintplex-Labs/anything-llm#1964]
### What would you like to see?

Multi-model support for the same provider, e.g. Local AI or Generic OpenAI.

**Comment by timothycarambat** [comment]
This is already supported for any models that support dynamic loading **and** have a `/models` endpoint.
https://github.com/Mintplex-Labs/anything-llm/blob/3457cc4b7a19f003b4fa3f7654b19f449249d5f9/frontend/src/hooks/useGetProvidersModels.js#L5

Generic OpenAi does not because we do not have multiplex inputs (type + select) since not every openai compatible endpoint has a model endpoint
