### ISSUE TITLE
[BUG]: LM Studio

### ISSUE THREAD

**Issue by nugecom** [Mintplex-Labs/anything-llm#1977]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

LM Studio is not listed as an LLM Provider in the drop down menu in the Linux version

**Comment by timothycarambat** [comment]
It most definitely is. The only conditional LLM on Linux is the built-in LLM. Please either scroll down in the input or type in LMStudio

**Comment by nugecom** [comment]
Screenshot attached. LM Studio is not there!

**Comment by timothycarambat** [comment]
There is no screenshot attached

**Comment by nugecom** [comment]
It got stripped from my email reply. Trying again online. ![Screenshot from 2024-07-26 18-30-17](https://github.com/user-attachments/assets/9a4527a8-82b3-42c3-a89d-e1044568afea)

**Comment by timothycarambat** [comment]
Oh, that is the workspace specific provider!

LMStudio has not been updated yet to support multi-model loading so we have it disabled.
https://github.com/Mintplex-Labs/anything-llm/blob/0cba89a54bb78ec074ea8a8faf70fd354406e3e6/frontend/src/pages/WorkspaceSettings/ChatSettings/WorkspaceLLMSelection/index.jsx#L19

You can use it if you have LMStudio as your _system_ level provider, but it is not currently for workspace specific support at this time.

Its probably time we do allow that to happen since you can _technically_ do playground now and we do allow it for agents. I can remove that filter then. It would be in the next patch (1.5.13)

**Comment by timothycarambat** [comment]
Done 013c0b9575ae6a87af87275e326041c4e0afeeee

**Comment by timothycarambat** [comment]
@nugecom Ah totally understand the desire to not hop between apps.

So we recently just made 1.5.12 live where you can import any downloaded GGUF file. In the subsequent updates, we are hoping to expand this to be a model gallery/browser for the same reason you just voiced.

If you are non-technical you may find [LMStudio very nice](https://lmstudio.ai/) - its a full GUI app, with no terminal commands or anything but it is still another app :/

**Comment by nugecom** [comment]
![Screenshot from 2024-07-29 15-03-42](https://github.com/user-attachments/assets/a04919f3-11f9-4ff3-a1f6-e95df2027f3a)
Good move bringing LLM file management into your app. Local AI should be as easy as online AI for the non-techies - creating a clickable app on install that can be pinned to the desktop menu for example. I've just realised the distinction between system level and workspace level you mentioned. Import feature is disabled for Linux in 5.12 though - screenshot attached.
