### ISSUE TITLE
[BUG]: OpenRouter always cut off it's response

### ISSUE THREAD

**Issue by PierrunoYT** [Mintplex-Labs/anything-llm#1983]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

[BUG]: OpenRouter always cut off it's response

![grafik](https://github.com/user-attachments/assets/be99913e-f398-4423-a60e-d65f4e9b7d45)
![grafik](https://github.com/user-attachments/assets/c00eef2d-9cf5-42d4-a072-71be73aeb60b)

**Comment by PierrunoYT** [comment]
https://discord.com/channels/1114740394715004990/1266674095286784051
https://discord.com/channels/1114740394715004990/1248000016786919546

**Comment by timothycarambat** [comment]
What models are you using on OpenRouter so we can replicate - latency matters a lot because OR does normally return `done` finish responses :/

**Comment by PierrunoYT** [comment]
> What models are you using on OpenRouter so we can replicate - latency matters a lot because OR does normally return `done` finish responses :/

I used Claude and ChatGPT but I think it will be on all models.

**Comment by timothycarambat** [comment]
Using `meta-llama/llama-3-8b-instruct`
<img width="1374" alt="Screenshot 2024-07-29 at 11 23 13 AM" src="https://github.com/user-attachments/assets/98a27d0b-2c02-48b7-9644-50dfba1f4068">

Using `meta-llama/llama-3.1-8b-instruct:free`
<img width="1412" alt="Screenshot 2024-07-29 at 11 24 39 AM" src="https://github.com/user-attachments/assets/9f61cc0f-2b72-447c-b6f0-4bc7f9b27b46">

Using GPT/Anthropic and other random models I get responses as well.

I think the issue here is the whole issue with OpenRouter we have to work around for here:
https://github.com/Mintplex-Labs/anything-llm/blob/296f04156455346a35cec4440239325523265d33/server/utils/AiProviders/openRouter/index.js#L164

Your internet connection to the model may be just slow enough per token response that you exceed the 500ms timeout which leads to the response being cut off. I have 5GB download, so my internet speeds are quite fast and that may not be the case on your and others ends.

We can make this timeout a config?

**Comment by PierrunoYT** [comment]
Can you check this 
![grafik](https://github.com/user-attachments/assets/00b5495e-f757-46e3-866f-eb45e078db0d)

Not sure how we can fix this issue.

**Comment by timothycarambat** [comment]
That is not the issue.

**Comment by PierrunoYT** [comment]
> That is not the issue.

Okay then he was wrong.

**Comment by timothycarambat** [comment]
Unless you are sending massive prompts the max_tokens response would not impact your output, which is not what the examples showed how you replicated the issue

**Comment by PierrunoYT** [comment]
@timothycarambat 
![grafik](https://github.com/user-attachments/assets/fa44e980-0b0d-4e6c-9cc1-c6866d872945)
it's still cutting of but it works better since the last update

**Comment by PierrunoYT** [comment]
@timothycarambat I set it to 1000 and I still get this 
![grafik](https://github.com/user-attachments/assets/238ef5f7-e59c-4bce-857a-7d57b9ecfb2c)
