### ISSUE TITLE
[BUG]: Error when using Perplexity Online models

### ISSUE THREAD

**Issue by jmbenedetto** [Mintplex-Labs/anything-llm#1990]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Perplexity online models return an error message, as if the model was not available in Perplexity.

"400 Invalid model 'llama-3-sonar-large-32k-online\*'. Permitted models can be found in the documentation at https://docs.perplexity.ai/docs/model-cards."
<img width="766" alt="Screenshot 2024-07-28 at 3 51 28 PM" src="https://github.com/user-attachments/assets/62cf7cdf-a629-4385-8a13-e8944933fb6f">

### Are there known steps to reproduce?

- Go to space settings.
- Go to chat settings.
- In "Workspace LL Provider" select Perplexity AI.
- In "Workspace Chat model" select any online model.

<img width="1352" alt="Screenshot 2024-07-28 at 3 51 52 PM" src="https://github.com/user-attachments/assets/f2fcf206-1281-4c6e-8ed1-d0d08f421da2">

**Comment by timothycarambat** [comment]
Looks like the sync script did not omit their bold text. We have to manually update their model listing because for _some reason_ they will not provide a `/models` endpoint. Will patch now. If you are on desktop it will be present in the next update.

https://github.com/Mintplex-Labs/anything-llm/blob/ae58a2cb0db7c74d9c43c3f8ac748725e28ab31c/server/utils/AiProviders/perplexity/models.js#L2
