### ISSUE TITLE
[BUG]: "Generic OpenAI" LLM Provider can not be edited

### ISSUE THREAD

**Issue by cougarten** [Mintplex-Labs/anything-llm#2016]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Selecting "Generic OpenAI" in a workspace for the first time shows all the settings/input fields to set it up. Once confirmed it is impossible to get back to this settings screen to change things.

Ugly workarround: delete the config for "Generic OpenAI" manually.

### Are there known steps to reproduce?

**Steps to reproduce:**
- start with an installation that has "Generic OpenAI" LLM Provider set
- create a new workspace
- go to settings -> "chat settings", of that workspace
- select "Generic OpenAI" as the LLM Provider
- enter any details so it allows you to save (does not have to work)
- (optionally: close the settings, try using the workspace)
- go to settings -> "chat settings" again
- (optionally: choose any other LLM Provider)
- choose "Generic OpenAI" as teh LLM Provider again

*Expected Outcome:*
- The initial pop-over dialog appears again
- I see the details I previously entered
- I can change the connection settings

*Actual outcome:*
- I can select "Generic OpenAI", but no pop-over dialog appears
- even new workspaces don't show it

**Comment by linxiaohui** [comment]
+1

**Comment by shatfield4** [comment]
@cougarten @linxiaohui Can you please explain to me what your use case is for this feature? Implementing this will take significant backend changes because the way we have providers setup currently, you cannot change things like the base URL, API key, context windows, or max tokens easily. We can however add a model field to this provider.

Is your goal to use multiple different providers using the Generic OpenAI provider in the workspace? If so please let us know which providers you are using and we can add these as additional providers so you don't have to use the Generic OpenAI provider to do this.

If your goal is to use the same provider but with different models I will be adding an input field to this provider.

**Comment by linxiaohui** [comment]
> @cougarten @linxiaohui Can you please explain to me what your use case is for this feature? Implementing this will take significant backend changes because the way we have providers setup currently, you cannot change things like the base URL, API key, context windows, or max tokens easily. We can however add a model field to this provider.
> 
> Is your goal to use multiple different providers using the Generic OpenAI provider in the workspace? If so please let us know which providers you are using and we can add these as additional providers so you don't have to use the Generic OpenAI provider to do this.
> 
> If your goal is to use the same provider but with different models I will be adding an input field to this provider.

for me, it is because I had wrongly set the parameters, and wanted to change them
