### ISSUE TITLE
LLM downloads stuck at 50-60% [BUG]: 

### ISSUE THREAD

**Issue by dan8798** [Mintplex-Labs/anything-llm#2038]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I've downloaded and installed anythingllm desktop on win11. Everything went fine, except when i try to download llms such as llama3.1 etc, it won't complete, no matter which llm i try to download. I've uninstalled and reinstalled anythingllm desktop to no avail, frustrating.

### Are there known steps to reproduce?

 I've uninstalled and reinstalled anythingllm desktop. I"ve tried all the other llms, they all won't complete downloading.

**Comment by timothycarambat** [comment]
This is not a bug with AnythingLLM, but likely from ollama's model registry - which is where the download stream originate from. We have seem download's hang from people who have limited disk space where AnythingLLM is using storage _and_ with VPNs. Do either of these apply to you?

I downloaded llava-llama3 on a fresh windows desktop today actually - no issues

**Comment by dan8798** [comment]
None applied, not using vpn and plenty of space on my hard drive. I download with ollama, webui and others and never encountered this issue.

**Comment by mercs759** [comment]
Same situation here : Win10pro on intel 6500T, 16GBram , 40Gb Free SSD space.
Gpt4all goes fine, Lm Studio goes fine, Anything stops downloading models between 40 and 56%

**Comment by kckcki** [comment]
My runtime environment / computer:
─────────────────────────────────────
■  Lenovo ThinkPad P53 Laptop
■  8TB SSD space = 2 x 4TB built-in SSDs on PCIe Bus
■  64 Gigabytes of RAM
■  CPU: Should Not matter
■  GPU: Should Not matter
■  Windows 11 Enterprise LTSC
■  Type of Internet Connection: Should Not matter
 
1)  YES I wasted 45 gigabytes of my internet data due to the AnythingLLM download getting stuck !

2)  I had to redo/repeat the download over 9 times :((

3)  I lost a WEEK, redownloading the model (LLaVA Llama3 8B  5.5GB) :((

4)  At the END of the week, I was at a point where I was willing to completely give up on this rather promising LLM ::(( Having wasted 45 gigabytes of my internet data :((


Initial Symptoms:
─────────────────────────────────────
While AnythingLLM was running
I went into my folder
c:\Users\User1\AppData\Roaming\anythingllm-desktop\storage\models\ollama\blobs
we should call this the “blobs” folder.
 
and Lo and Behold, I found these files

sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-0
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-1
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-2
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-3
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-4
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-5
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-6
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-7
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-8
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-9
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-10
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-11
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-12
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-13
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-14
sha256-b6e1d703db0da8227fdb7127d8716bbc5049c9bf17ca2bb345be9470d217f3fc-partial-15
 
a)  The first file without a number suffix, is 4.58 gigabytes in size !
b)  The REST of the files were super-tiny and almost empty, each of them was less than 200 bytes in length.
c)  These files struck me as CLEARLY the files that make up the so-called Model, i.e. the Model BEING DOWNLOADED and AnythingLLM FAILING to COMPLETE the download process.
 
The first file, when I . . .

right-clicked it and 
    checked its Size by looking at its reported “Size on Disk”
    closed the file size window (Properties dialog box), and waited 4 to 10 seconds
right-clicked it AGAIN/afresh and 
    checked its Size afresh by looking at its reported “Size on Disk”

. . . I could clearly see and tell whether it was GROWING in size or just STUCK at one size.

When the download is NOT stuck (working fine, truly and busy downloading),
the file would be GROWING at a rate of 11 megabytes per second, indicating that NOT only was my internet speed fast, but SOMEONE was writing data to this file and causing it to GROW, with it occupying more and more disk space.

on the OTHER hand, when the download was STUCK (while AnythingLLM continued to show a FAKE progress indicator spinning circle!!),
the file’s “Size on Disk” would be sitting at ONE value, indicating that the file is NOTTT GROWING, and that NO ONE is writing data to this file as it is NOT progressively occupying more and more disk space :(

 
Typical First Line Intervention:
─────────────────────────────────────
For most of us, we would naturally be tempted to attempt the following (in the order of least disruption)
a) STOP the download, or
b) CLOSE the app and restart it, or 
c) just uninstall the app and wipe everything out (clean sweep), and re-install the whole app afresh.

 
Unearthing the Bug:
─────────────────────────────────────
I have PROOF that AnythingLLM, contrary to its claim on its user interface,
whenever you STOP the download [within the app, top right corner]
it tells you that your Download can be RESUMED later, which is a FALSE claim :((

the claim is FALSE because once you STOP the download [within the app, top right corner], or you CLOSE the App’s window
it actually DELETES ALL the already/partly downloaded files in the blobs folder
    c:\Users\User1\AppData\Roaming\anythingllm-desktop\storage\models\ollama\blobs

these partly-downloaded files can be GIGABYTES of WASTED data in the case of you stopping the download at 80% and they get deleted like this !! :(( and that is exactly HOW I ended up wasting 45 gigabytes of my internet data through repeated fresh re-downloads :((

I know FOR SURE that it Deletes the partly-downloaded files, because 

a) While watching in the folder, as soon as I STOP the download [within the app, top right corner], or CLOSE the App’s window, I could witness the partly-downloaded files disappearing (ALL of them) :((

b) With my partly-downloaded files GONE, I would then look for the files by their age and size (Not by their name!) and I cud Not find traces of them ANYWHERE on my hard disk :(( I had hoped that it was MOVING the files to another hidden location so that it may return them BACK to the blobs folder for it to RESUME the download when you relaunch it, as it [falsely] claims. The truth however is that AnythingLLM does Not competently know what “RESUMING” a download means :((

c) My FREE DISK SPACE increased by a warping 5 GB as soon as I STOP the download or close the window !! This one was the last nail in the coffin and it was ENOGHT for me to conclude that . . . AnythingLLM definitely DELETES partly-downloaded files (leaving No hope for resumption of the download).

This brings us to the END of the PROBLEM Description.

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
 

Now let’s get to the SOLUTION :))
─────────────────────────────────────
 
When my download reached 98% in the new week, it got STUCK :((

1)  I went into the blobs folder and I COPIED away ALL of my partly-downloaded files

2)  I pasted them into my own backup folder  C:\A\Save_My_Partly_Downloaded_Blobs
     we could call these “RESCUE COPIES” or “backup copies”.

3)  I then proceeded to STOP the download [within the app, top right corner], I could have also CLOSED the App’s window

4)  The partly-downloaded files disappeared from the blobs folder as expected :)) This time around I was smiling, knowing that I had my own RESCUE COPIES of my 98% partly-downloaded files :))

5)  I COPIED BACK the RESCUE COPIES of my 98% partly-downloaded files from
    C:\A\Save_My_Partly_Downloaded_Blobs
to the 
    blobs folder

6)  I relaunched AnythingLLM
     Lo and Behold, the download indicator within AnythingLLM showed that my download was at 98% and it rapidly RESUMED to 99% :)) Within 2 minutes the download was at 100% and AnythingLLM was Un-Packing the download :)))

I was so EXCITED I had the motivation to come here and WRITE this whole Essay :)))

It’s been two weeks, and I am proud to say that I have the “LLaVA Llama3 8B  5.5GB” model running locally inside of my AnythingLLM installation and EVERYTHING else about my ordeal HISTORY :))

Subject / Topic: 
Downloading of the Models gets stuck during installation of AnythingLLM.

Google Search Engine Keywords: 
AnythingLLM, downloading of model does Not complete, downloading of model is stuck, downloading model does Not resume, downloading model does Not finish, fails to resume model download, model download starting from scratch, model download starting afresh, closing and reopening AnythingLLM does not help /work, resintalling AnythingLLM does not help / work. I’ve tried everything.

kind regards
this is Tebza a.k.a. Kcee, all the way from the City of Johannesburg, South Africa, on the continet of Africa
last updated : Thursday, 30 January 2025, 12:31

██ End ███████████████████████████████████

**Comment by timothycarambat** [comment]
Ollama's registry has been having cloudflare issues all week 
This has resulted in hanging downloads, stuck downloads, failures to unpack layers, and it has been intermittent. All we do it pull from their registry so there is little for us to do to make it _work_. Since it is wholly dependent on their registry working and also the client connection persisting it.
