### ISSUE TITLE
[BUG]: Embed document of pdf failed

### ISSUE THREAD

**Issue by sfdeggb** [Mintplex-Labs/anything-llm#2042]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When I tried to upload a text PDF document to use the embedded model, the embedding failed: an error message was displayed
![image](https://github.com/user-attachments/assets/72c35ce1-9622-453d-b26c-757714c16b24)
When I tried embedding with a test txt document, it appeared correct.
![image](https://github.com/user-attachments/assets/fd3a4e22-7d01-4256-9b83-817337541566)
When I tried to view the server log, it showed:
![image](https://github.com/user-attachments/assets/12a7c1f9-1fb3-49b1-95e4-c0a9a5258100)

except helpful solution!

### Are there known steps to reproduce?

1. LLM: ollama gemma2:2b
![image](https://github.com/user-attachments/assets/aa4b2a6d-7eb3-4c04-9f57-122df05d3fac)
2. vector database: LanceDB
![image](https://github.com/user-attachments/assets/3c02ef2f-a83c-49a9-aa4d-c5bdf2e5d59a)
3. embeding model : nomic_embed_text_least
![image](https://github.com/user-attachments/assets/b3949e90-cb54-4efe-9289-7cdd8c3a9ad1)
4. Max Embedding Chunk Length: 509
![image](https://github.com/user-attachments/assets/11631b4e-f35e-46ee-a727-d83f90f47ee5)

**Comment by timothycarambat** [comment]
This is an error wth your Ollama client, not AnythingLLM. We are simply reporting the error back to let you know it failed. Ollama returning a 499 indicates the model could not be loaded due to VRAM constraints - you likely do not have the system specs to hot load both an LLM and embedder into the system memory. You should remove the keep alive setting you modified as that is probably locking up the system memory preventing the embedder from loading.
