### ISSUE TITLE
[BUG]: Possible context trunking issue in version 1.6.2

### ISSUE THREAD

**Issue by Taluen79** [Mintplex-Labs/anything-llm#2100]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hi!

I was having a rather long coding session with Llama 3.1 via Groq and suddenly notices some weird reply from the LLM. So I made a fork from the thread where there reply started to sound inconsistent. I then asked the LLM to repeat my most recent message. It cited something way far back, like it has forgotten our most recent discussion, but remember what was said long ago.

I have repeated this test a few times and it seems that after a certain limit, something fishy is being done to the chat history. It feels like the trunking of message history is done incorrectly after a certain limit so that instead of remembering the most recent messages, it instead remembers the start of the conversation but forget everything that has been said recently.

I was using a chat history length of 25 in the workspace settings.

### Are there known steps to reproduce?

Just have a very long chat and pay attention to what the LLM is saying, if it starts drifting of from the current topic, make a fork from the thread and then ask it to repeat your most recent message that it can remember.

**Comment by shatfield4** [comment]
What you're experiencing is actually due to our messageArrayCompressor function.

You can read through the comment [here](https://github.com/Mintplex-Labs/anything-llm/blob/dfb951e9cf278e06273e9d0ccae1f4cca537fc2e/server/utils/helpers/chat/index.js#L7-L22) explaining why this is happening and our reasoning for implementing this.

As you said it only happens when you have a very long chat and that is how this is intended to work. This function is only used when you use the entire context window of the model you are using and we need to compress your messages in order for it to fit.

**Comment by Taluen79** [comment]
Why not only cannonballing in query mode and use other methods to retain recent memory when chatting?

Don't want to dwell on this. I'm just pointing out that the issue exists and that it might become more prevalent when the app gains more popularity. People will not only use it for chatting with documents.
