### ISSUE TITLE
[BUG]: AMD GPU NOT (WASN'T) BEING UTILIZED for AnythingLLM for LLM Provider.

### ISSUE THREAD

**Issue by daveycombs** [Mintplex-Labs/anything-llm#2115]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When using AnythingLLM as the LLM Provider with my AMD 6800xt the GPU wasn't being used. With a separate Ollama instance of 0.3.6 would use my GPU I replaced the older 0.3.4 Ollama (llm.exe) files and folders in anythingllm/resources/ollama I also included the additional rocm folder from 0.3.6 which seemed to fix the issue.

I also tested Ollama 0.3.6 with and without rocm and it would not utilize the GPU without rocm included

![floorp_D9TCdNZzIi](https://github.com/user-attachments/assets/cfdb7766-a0b5-473c-b52f-e55b342fcbbf)

**Comment by timothycarambat** [comment]
This is already a known issue and is being track off-github since the desktop electron wrapper is not part of the OSS Repo, but yes, the reason AMD cards wont be leverage is due to ROCM not be included in Ollama - we currently prepack the llama_runners into the app but doing so will bloat the app to multiple GBs, so we will be implementing a post-install script to download the required resources so that rocm and other runners will be present

**Comment by crnisamuraj** [comment]
any update on this? anythingLLm desktop is still running models on CPU on linux with AMD GPU
