### ISSUE TITLE
[FEAT]: Please make file names of downloaded components human-readable

### ISSUE THREAD

**Issue by mtomas7** [Mintplex-Labs/anything-llm#2144]
### What would you like to see?

First of all, thank you for a great product that slowly takes a shape into becoming an all-in-one solution for local AI needs! I'm currently using LM Studio, but after last update with added local AI models (it was great to see that I can easily import GGUF models from my library) and speech recognition, I see this may be a good replacement of LM Studio/Ollama and OpenWebUI.

After importing a GGUF model, I noticed that I could not easily find it's location. Usually, I just look at my .cash folder to manage my AI library. In this case Qwen2 model was saved as:

\Users\UserName\AppData\Roaming\anythingllm-desktop\storage\models\ollama\blobs\sha256-945823750c8eb........

Similar situation was with downloaded Piper voices, they were stored in obscure:

\Users\UserName\AppData\Roaming\anythingllm-desktop\File System\000\t\00\00000015

Where one files would have meta info of the voice model and next file would be voice model itself.

I think it would be great that all downloaded components would be under one location and named according to type and have human-readable names, eg:

\Users\UserName\AppData\Roaming\anythingllm-desktop\storage\models\ollama\blobs\Qwen\Qwen2-7B-Instruct-GGUF\qwen2-7b-instruct-q8_0\ (all files related to this particular model)

\Users\UserName\AppData\Roaming\anythingllm-desktop\storage\voices\piper\arctic\ (meta and voice files for arctic voice model)

Thank you!

**Comment by timothycarambat** [comment]
I agree, that would be nice to have, however, we don't control those aspects. PiperTTS downloads the blobs so the [JS port of PiperTTS](https://github.com/rhasspy/piper) can work. And for the LLM, that is Ollama and the SHA hash of the blobs is a very common complaint people voice often on Reddit/GitHub. Some people even have made tools to make it more sensible when looking in ollama's model directory.

There is a reason for doing it and it has to do with how they download layers from their registry and keep track of what version your downloaded model might be when compared to the registry. Annoyingly, it also duplicates any GGUF you import into a blob as well in that folder. Just how it works.

Either way, both of these things are not something we will influence since it will likely break each respective integration and make updating them more difficult or unable to work when pulling models they need or the user wants
