### ISSUE TITLE
[BUG]: Default Vector Database LanceDB not compatible with text-embedding-ada-002

### ISSUE THREAD

**Issue by davadev** [Mintplex-Labs/anything-llm#2156]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I got this error when trying to chat in my workspace.

> Could not respond to message.
> Failed to execute query stream: Invalid input, No vector column found to match with the query vector dimension: 1536

I found this [article](https://medium.com/@epappas/dealing-with-vector-dimension-mismatch-my-experience-with-openai-embeddings-and-qdrant-vector-20a6e13b6d9f) pointing that this issue is likely caused by the vector database expecting different dimensions.

If this can be configured, it would be useful to know where, or add the configuration option in anythingllm

### Are there known steps to reproduce?

Set LLM to openai **GPT-4o-mini** and the embedding modell to **text-embedding-ada-002** while keeping the default database LanceDB.

**Comment by timothycarambat** [comment]
It is compatible, what you did was you embedded something into the workspace using the (likely) default embedder which is 386 dimensions. 
- You then removed that document from the workspace, swapped embedders to text-embedding-ada-002
- Probably did not see the warning telling you that this error would occur!
- then embed a new doc into the same workspace which now expects 386 dimension vectors.
-Embedded the text worked, but failed to upsert because the table schema was already set.

Solution:
Open workspace settings > Vector database > Reset Vector Database
Now you can insert you new document. You should also delete the previously embed document or else you will get an error when you try to insert it into the 1536-dimension table.

Workspace vector tables infer their dimensionality on the first embedding. Afterward, this property is immutable until the db is reset or the workspace deleted.

Did you not get an error when swapping models? You should have seen a popup alerting you that this would need to be done.

https://docs.anythingllm.com/setup/embedder-configuration/overview#supported-embedding-model-providers

**Comment by davadev** [comment]
Sorry, apparently my steps to reproduce were not complete. I did see the warning, and did reset the workspace several times and then reimport the documents again. I even deleted the workspace and created new one where I only used openai LLM and embedder. Could it be the reset is not working properly?

**Comment by pm7y** [comment]
I am also seeing the same issue.

**Comment by davadev** [comment]
Good to know, I only got rid of it after Reinstalling…

**Comment by timothycarambat** [comment]
You could have just reset the workspaces vector DB or deleted the workspace and/or previously embedded documents

**Comment by pm7y** [comment]
Mate, we're both saying we tried that but it didn't work.

**Comment by DangerousBerries** [comment]
I deleted all documents before changing the embedding model and reuploaded all documents, also got this error.

**Comment by timothycarambat** [comment]
@DangerousBerries you need to delete the workspace (this deletes the table). Or you can open the workspace's settings >Vector database > Reset vector database. This does the same.

The lanceDB _table_ schema is set on the first seen vector, removing all the documents just results in no documents in the table, not modification of its schema

**Comment by DangerousBerries** [comment]
> @DangerousBerries you need to delete the workspace (this deletes the table). Or you can open the workspace's settings >Vector database > Reset vector database. This does the same.
> 
> The lanceDB _table_ schema is set on the first seen vector, removing all the documents just results in no documents in the table, not modification of its schema

Yeah that worked thank you.

**Comment by kabaluyot** [comment]
Re-uploading  the files after resetting vector database works
