### ISSUE TITLE
An error is reported when moving the pdf to the workspace

### ISSUE THREAD

**Issue by brownplayer** [Mintplex-Labs/anything-llm#2172]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I use the ollama api (ollama is deployed locally), I can chat normally in the workspace, and the content returned by the background ollama server also proves that the local ollama server works properly. But when I finished uploading the documents and moved them to the workspace, the system showed an error:
[Failed to add batches to table motor: lance error: LanceError(Arrow): Invalid argument error: Values length 17280 is less than the length (768) multiplied by the value size (768) for FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 768), C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lance-datafusion-0.12.1\src\utils.rs:41:28]
![image](https://github.com/user-attachments/assets/e010fc5a-272b-4320-8b1b-edb20b799f83)
![image](https://github.com/user-attachments/assets/5c6b5a55-106f-4d92-bed6-d78f478ce536)

**Comment by iqs-systems** [comment]
Same

**Comment by brownplayer** [comment]
I found a fix. I hope it helps you, too. I downloaded anythingllm before but later deleted it, perhaps because the registry or some other attached files were not completely deleted, which caused this error when installing again. I used the tool HiBit Uninstaller to re-delete anythingllm. It is worth mentioning that after deleting the program with this tool, we must use advanced scanning and cleaning the relevant information of anythingllm, including the registry information. Get your computer ba

---- Replied Message ----
| From | ***@***.***> |
| Date | 08/25/2024 16:46 |
| To | Mintplex-Labs/anything-llm ***@***.***> |
| Cc | brownplayer ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Mintplex-Labs/anything-llm] An error is reported when moving the pdf to the workspace (Issue #2172) |

Same

**Comment by timothycarambat** [comment]
What? This is because your embedder model returned something badly or the vector db table was not in alignment with your embedder model dimensionality. If you changed your embedder model at any point you can no longer use your workspaces that have content in them, because the embedder model no longer matches what was used to embed content.

Typically, you can just delete the documents and reset the vector DB on the workspace's settings and reupload and embed and be done.

If you uninstall anythingllm that uninstalls the program, the storage folder, which has all your documents and workspaces can be found here https://docs.useanything.com/installation/desktop/general and you can just delete that. No need to install any third-party or scanning tool, its just a storage folder of files used by the app. You can just delete it
