### ISSUE TITLE
[BUG]: Documents processing API is not online

### ISSUE THREAD

**Issue by venturaEffect** [Mintplex-Labs/anything-llm#2173]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Trying to upload a mp3 file got this error twice on different audio files.

### Are there known steps to reproduce?

Just tried to upload on a fresh new installed AnythingLLM desktop app on Windows 11.

And btw is it also possible to upload mp4? What will it take from it? What happens in the screen and transcribes also the audio?

Apprecaite your time.

**Comment by timothycarambat** [comment]
Depending on the resources available on the machine this can be quite intensive to do. The audio file needs to be converted to .wav then processed. MP4 is not supported, even if that was the case it would still need to strip the audio first.

Logs from anything crashing would be helpful https://docs.useanything.com/debug since it seems you can upload, but then something goes wrong
