### ISSUE TITLE
[FEAT]: Login with Google Authentication

### ISSUE THREAD

**Issue by Peterson047** [Mintplex-Labs/anything-llm#2191]
### What would you like to see?

I'm implementing the solution via Docker, and in user management, the user's demand to log in with Google came up. Is implementation possible?

**Comment by timothycarambat** [comment]
See this PR https://github.com/Mintplex-Labs/anything-llm/pull/1326

It is not merged currently due to a holdup on complexities because we need to also abstract this away from the core ecosystem or modularize it totally because currently it is a bit too embedded and there is no supporting documentation to set it up. If you know how to make a Google App though, its very straightforward to pull in an implement.

Since there is not docker image for each PR, you'll need to pull and rebuild a new image that includes this PR until merged.
