### ISSUE TITLE
[BUG]: Agent with webscraping is hallucinating

### ISSUE THREAD

**Issue by jeremiasbaur** [Mintplex-Labs/anything-llm#2208]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I discovered a bug while using the agent with the web-scraping command.

I was trying to scrape multiple lecture pages to generate a structured format so I can paste the content into an excel file. I instructed my agent in what information I am interested in and then started it with the first webpage. For the consecutive webpages, I was using this command:

@agent
Do the same for:
@web-scraping www.website.com

Sometimes, the agent correctly accessed the webpage and gave me the correct information. However, if I instantly sent the next command with the next website, the agent didn't scrape the website and just hallucinated some lecture information. If I only send the command after e.g. 30s, everything works well. I know that I don't need to use @agent every time but it shouldn't change anything, right?

Why does this happen and how can you / I fix it?

**Comment by pleabargain** [comment]
Which v. of the desktop are you using? OS?

**Comment by jeremiasbaur** [comment]
I am using the version 1.6.4

**Comment by timothycarambat** [comment]
When the `@agent` session closes it does not keep the previous session data (like an entire website) in memory. If you want to persist the data of a whole website that was scraped use the actual website scraper and embed it is a document. Ephemeral data an agent accumulates during a session is currently not persisted between sessions since it may not be useful after the session is completed.

If you dont send a chat for 30s, the session can close and the UI will report this as `agent session ended` in which sending a chat afterwards is like using regular rag.
