### ISSUE TITLE
Native LLM Provider "waiting for models" to populate

### ISSUE THREAD

**Issue by Ace-Rimmer-Space-Adventurer** [Mintplex-Labs/anything-llm#2234]
What would cause my "model selection" drop down to no populate any models? 
![image](https://github.com/user-attachments/assets/42ff1a20-aafb-40e8-a64c-37191223f411)

AnythingLLM is built on CasaOS. I'm accessing it through a browser:3051 
Other Apps on CasaOS can comm back and forth to the internet no problem. 

Seems like AnytingLLM is having some comm issues. 

If i switch to Anthropic LLM Provider w/ my key configured I get this error when chatting. 

"Could not respond to message.
An error occurred while streaming response. NetworkError when attempting to fetch resource."

Where are the logs stored? Is there a command line tool / commands to test? 
I want to help. 
Thanks
Ace

**Comment by timothycarambat** [comment]
> What would cause my "model selection" drop down to no populate any models?

No GGUFs in the storage directory. Since you put your issue in the wrong repo (docs vs product!) the template asks how you are using AnythingLLM. I would presume this is in docker  since we dont offer native support in desktop - which would mean all storage is in whatever you set as `STORAGE_LOCATION` when booting the container.

eg: ```shell
export STORAGE_LOCATION=$HOME/anythingllm && \
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
``` 
=> models would be in `$HOME/anythingllm/models/downloaded`
https://github.com/Mintplex-Labs/anything-llm/blob/master/server/storage/models/README.md#where-do-i-put-my-gguf-model

Since you are in docker, logs are in `docker logs <CONTAINER_ID>` and will likely tell you why you cannot reach outbound to Anthropics API or otherwise
