### ISSUE TITLE
[BUG]: Document Processor Unavailable

### ISSUE THREAD

**Issue by redkit75** [Mintplex-Labs/anything-llm#2242]
### How are you running AnythingLLM?

Local development

### What happened?

I installed the application on Ubuntu.
It's not possible to upload files. It gives the following error, and I can't even select a file to upload.

**Document Processor Unavailable**
We can't upload your files right now because the document processor is offline. Please try again later.

**Comment by timothycarambat** [comment]
`yarn dev:collector`
https://github.com/Mintplex-Labs/anything-llm?tab=readme-ov-file#how-to-setup-for-development

**Comment by fengnex** [comment]
@timothycarambat your method does not work
I successfully executed yarn dev:collector but still got the same error when trying to upload a document:
Document Processor Unavailable
We can't upload your files right now because the document processor is offline. Please try again later.

How to fix the problem?

**Comment by ZhangQ714** [comment]
Check whether any other programs (such as Nginx) are occupying port 8888. Terminate those programs or change them to use a different port, then restart the collector.
