### ISSUE TITLE
[DOCS]: Could you add an example or instructions for web search with SearXNG ?

### ISSUE THREAD

**Issue by Richter03** [Mintplex-Labs/anything-llm#2257]
### Description

I try to set "SearXNG API base URL" like "http://127.0.0.1:1234/?format=json&q=%s" but it not work, I don't know what's should I looking for, I try to search but still have no clue that SearXNG API base URL I use is correct. I dock SearXNG via Docker WSL and set it able to return as JSON but still no clue what's wrong.

**Comment by Richter03** [comment]
Thanks, however it' doesn't work on Windows desktop version, I try `http://host.docker.internal:1234/` , `http://host.docker.internal:1234/search?q=<query>` and `http://host.docker.internal:8888/search?q=q%s` , non of them work, I try it on Open WebUI, `http://host.docker.internal:8888/` could connect to AI and use web search normally so do I need to set or change anything other from set AI agent and turn on web search on Windows desktop version ?

**Comment by timothycarambat** [comment]
Are you sure the agent is not just _refusing_ to call the tool and that tool is setup up fine? 

The correct value is indeed  just `http://host.docker.internal:1234`. And doing a query like `@agent search the web for  <xyz>` should then invoke SearXNG endpoint calls.

**Comment by stanribilir** [comment]
can we use searx online instances in anythingLLM, have you tested these and if there is a compatible one can you please tell. it is complicated for me to install my own searxng on my own, even with docker.

**Comment by joaovl5** [comment]
It's a bummer that it only allows for local-only searxng instances. I run my own on a vps and would it would be awesome to connect to it locally.

**Comment by timothycarambat** [comment]
You can absolutely use an external connection @joaovl5. its just a URL - if the client can reach it you can run it. AnythingLLM's connection to SearXNG can be any valid IP - it just need to resolve. There is no restriction on localhost, we couldn't even control that if we wanted to...

For everyone who keeps having issues with this - make sure `- json` is enabled as an engine in your `settings.yaml` for searXNG, otherwise all you can get is HTML back which would be wasteful for the LLM over just JSON response bodies.
