### ISSUE TITLE
[FEAT]: Name threads with AI generated summary text

### ISSUE THREAD

**Issue by glinkot** [Mintplex-Labs/anything-llm#2262]
### What would you like to see?

Right now I just see conversations shown as 'thread' and 'new thread'.  Other similar tools I've used use a lighter/cheaper LLM to generate a brief name for the chat, like "asking about dog breeds" or whatever.  This request was asking for it I believe (https://github.com/Mintplex-Labs/anything-llm/issues/701) but what was implemented was different to what I'm referring to.

**Comment by timothycarambat** [comment]
Yes, and the primary reason is latency. Not everyone is using a high (or even mid) tier performance device and the latency to a load the model, run inference, and store the text, with a high speed. Most would not be willing to wait an additional 1-2s for inference completion just to name a thread, which is why the implementation was different.

So as it stands now, which is naming a thread based on the first chat, this is both fast for any device and LLM implementation but gets the idea of delineating chat threads without the user needing to explicitly rename them. Add an LLM into that process for what amounts to a very minor UX improvement was considered extraneous and would hurt the UX on lower-end systems using local models.
