### ISSUE TITLE
[BUG]: "@agent" doesn't work in V1.6.7?

### ISSUE THREAD

**Issue by mecjy** [Mintplex-Labs/anything-llm#2291]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

"@agent" doesn't work in V1.6.7

Stop at 
"Agent @agent invoked.
Swapping over to agent chat. Type /exit to exit agent execution loop early."
or
Directly go to
"Agent session complete."

**Comment by mecjy** [comment]
Work nornally now ..
so strange

**Comment by trafficonese** [comment]
I have the same problem.. nothing happens with the agents

```
Agent @agent invoked.
Swapping over to agent chat. Type /exit to exit agent execution loop early.
Agent session complete.
```

**Comment by timothycarambat** [comment]
You can find logs here: https://docs.anythingllm.com/installation-desktop/debug

Agent closing early is almost always a user config issue:
https://github.com/Mintplex-Labs/anything-llm/issues/1793
https://github.com/Mintplex-Labs/anything-llm/issues/2248
& many more you can search in issues @trafficonese

**Comment by woss** [comment]
i'm having this in 1.7.7, fresh install with lm studio

**Comment by woss** [comment]
port 3001 is the problem. it can be changed by setting `SERVER_PORT` to a different port,  but this should be possible to either change in the UI or use very high value. For example i have other stuff running on my laptop, other services, one of them is on 3001, i noticed it by accident.

**Comment by timothycarambat** [comment]
On desktop, the backend will auto-hunt for a free port if 3001 is occupied - in your screenshot you can see the line - on Docker you can obviously change the host via the `-p HOST_PORT:3001` CLI. If running in development, then you can just set the ENV

https://github.com/Mintplex-Labs/anything-llm/blob/ae237cd7209da1c91f092548ed1c41ebe5ca4fa4/server/index.js#L134

And that is in the `.env.development` file created from the `yarn setup` command. It is all there, but settingit via the UI is not something we will support since if you are running outside docker, you likely know how to code so changing an ENV file is trival. It would also require a server restart anyway since you cannot change the express backend port while it is running without a reboot

**Comment by woss** [comment]
Hi @timothycarambat , 
Thanks for the reply. Indeed, I know how to code :) 

You mentioned that the backend will hunt the free port. I didn't see that behaviour in the `bootHTTP`; it just uses the port if the env is not provided.

In my case, this is not really the issue since I switched to docker, but for the other users, it might be. The `3001` is a common port, and there is a high chance it is already occupied. 

Maybe I missed the implementation of the `hunt for the port` that happens if there is any. Can you link it here?

**Comment by timothycarambat** [comment]
This is how it functions - uses this library. This is just a util we use in the electron wrapper that goes around this repo for the desktop app. https://www.npmjs.com/package/get-port
