### ISSUE TITLE
[BUG]: Speak Your Prompt isn't working

### ISSUE THREAD

**Issue by Sukomal07** [Mintplex-Labs/anything-llm#2298]
### How are you running AnythingLLM?

Local development

### What happened?

Speak Your Prompt isn't working. When clicking on microphone , it is started but speech to prompt is not working.

### Are there known steps to reproduce?

Click on microphone and start talking

**Comment by timothycarambat** [comment]
Browser permissions and/or STT is not supported in your browser but somehow is rendering the mic icon. 

Since you are on local development - it is almost certainly browser permissions, which you need to enable because you probably have it disabled from other local development projects or is your defaults (which wont prompt since not HTTPS)

**Comment by Sukomal07** [comment]
I gave the permissions, including the microphone. Although it is not working.
