### ISSUE TITLE
[BUG]:Can't open AnythingLLMDesktop on Win11

### ISSUE THREAD

**Issue by SirenOP** [Mintplex-Labs/anything-llm#2310]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

After I install AnythingLLMDesktop and clicked to start,there was no window displayed,but the task manager could see the process.Whether I restarted  program or uninstalled and reinstalled it,it couldn't run properly.
I expect to use it normally.

### Are there known steps to reproduce?

Now I just click to start,it will happen again.

**Comment by timothycarambat** [comment]
Without more information, this will be hard to trace:
- When installing are you installing for current user or all
- Are you installing this on your primary C:\ Drive or elsewhere?
- Are you the admin of the machine
- Can you run the app in debug mode instead of click on it to see what happens?

You can do this by opening the terminal in windows and dragging and dropping the desktop icon into the terminal and pressing enter. This is certainly limited to your client or setup, as if this was an issue pervasive to all installs we would have heard it it from all around the world.

**Comment by deedlyjrment** [comment]
I'm having this issue as well just fyi.  App worked fine for a few days and now does exactly what OP says

**Comment by deedlyjrment** [comment]
Ollama API offline and the cmd hangs retrying.  I've got a few installs of Ollama from other apps, so i'm sure something is breaking this, but this seems to be vulnerable to causing issue?

**Comment by deedlyjrment** [comment]
Just following up on this because I fixed my issue.  After running the .exe in debug mode, it indicated that the Ollama API wasn't working.  

I just went into my AppData/Roaming and deleted the entire "anythingllm-desktop" folder after an uninstall to get rid of any remnant files.

Reinstalling fresh after removing all folders and files fixed the issue.  Must have been some missing dependencies or something for some reason that wasn't getting updated with a reinstall.

Hope the OP gets help from this.  The app is great!

**Comment by timothycarambat** [comment]
Sounds like maybe the supporting ollama_lib files failed to download on installation previously - since that would be a big blocker and a reinstall would be the fix. We used to package that in the app, but then the download size was getting too big for the installer so we made it a runtime action during installation

**Comment by deedlyjrment** [comment]
I'm glad you posted the debug comment earlier.  I would have completely given up due to the lack of related topics online.  Thx again.  Using the app now and loving it.

**Comment by Samuelyilma** [comment]
Hi, I’m having a serious performance issue with the AnythingLLM Desktop app on my Windows 11 system (i7 8th Gen, 16GB RAM, Intel HD 620, SSD).

The app takes over 1–2 minutes just to launch, and then when I click on Settings, Workspace, or try to chat, it takes another 1–2 minutes to load each action.

The strange part is, it was working perfectly before I reinstalled Windows and AnythingLLM. Now it’s consistently slow — even when no models are loaded and Ollama is off.

I've tried a full reinstall, cleared AppData and Roaming folders, and I’m using the CPU-only Ollama version. CPU and disk usage stay low the whole time.

What could be causing this delay? Is there any known issue with SQLite loading, disk access, or the UI renderer that might explain it?

**Comment by timothycarambat** [comment]
> What could be causing this delay? Is there any known issue with SQLite loading, disk access, or the UI renderer that might explain it?

One thing that _can_ occur is with Prisma pulling a binary in for the runtime (windows x86_64) on first run, which will then be in the app folder, but this file is very small. Nobody else has reported such a slow boot times - do you see anything when loading the app in debug mode?
https://docs.anythingllm.com/installation-desktop/debug#anythingllm-debug-mode-on-windows

**Comment by Samuelyilma** [comment]
Thanks for the explanation. I’m not very technical, but I tried running the app in debug mode and didn’t see any clear errors — it just takes a long time to load everything.

The app itself doesn’t crash, but it takes 1–2 minutes just to open. After that, it works — but slowly. When I try to open Settings, Workspaces, or switch providers (like changing from Ollama to another one), it loads for a long time.

Interestingly, when I use the local AI model through Ollama, it responds quickly with no lag or errors. The issue mainly happens when I try to switch providers or access certain parts of the app.

Everything was working fine before I reinstalled Windows and the app, so I’m not sure what changed. CPU and disk usage stay low the whole time.

Can you help me figure out what might be causing this? And if possible, could you give me simple steps to check or fix it?

**Comment by timothycarambat** [comment]
In the above specs, you did not list any GPU (at least not an integrated one), and I am thinking that somehow or some way that could be related as it pertains to hardware acceleration for the renderer process. However, is this a _recent_ happening or something that has always been the case for as long as your have used AnythingLLM Desktop?

**Comment by Samuelyilma** [comment]
This is a recent issue. AnythingLLM Desktop was working perfectly before I reinstalled Windows 11. I’m using an Intel HD 620 integrated GPU, and after the reinstall, it seems like hardware acceleration might be causing problems. The app hangs for up to 2 minutes when opening or switching menus, especially Settings

**Comment by timothycarambat** [comment]
Do you know which version you may have been on prior to this issue? You can always download the legacy versions from their changelog patch page on our docs. Interested to know if this is bug we introduce or a client side issue

**Comment by Samuelyilma** [comment]
I’m not exactly sure which version I was using before the issue started, but it was working perfectly until I recently reinstalled Windows and AnythingLLM. After that, the latest version began having delays (slow to open settings, switch workspaces, etc.).
Since then, I’ve tried reinstalling from scratch
