### ISSUE TITLE
[BUG]: Basic Auth behind a reverse proxy is broken

### ISSUE THREAD

**Issue by Danoloan10** [Mintplex-Labs/anything-llm#2314]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

When deploying A-LLM behind a reverse proxy and configuring Básica Auth in the proxy, the app keeps rewriting the Authorization header to null, thus spamming the credentials popup and rendering the app unusable.

### Are there known steps to reproduce?

Deploy a reverse proxy configuration (for example, using nginx) and configure Basic Auth in the A-LLM endpoint).

**Comment by Danoloan10** [comment]
I'm trying to fix it in my fork for my personal deployment. Sucks bc it's much harder to use docker for a fork.

**Comment by timothycarambat** [comment]
This is not supported explicitly by the software, we use the `Authorization` header for our own auth system for single and multi-user and co-opting it will be something that will cause issues if you are trying to protect the app via Basic Auth.

Is there any reason the default built in auth system that used JWT will not suffice here? Otherwise this is out of scope for this use case

**Comment by Danoloan10** [comment]
I'll look into using JWT. I just wanted to put basic auth in the reverse proxy because I don't have any authentication service deployed in my domain, but I still want to (somewhat) protect the endpoint from the public. I just was wondering why the Authorization header must be overwritten to null, it seemed avoidable. Thanks for the response.
