### ISSUE TITLE
[BUG]: Issue with Embedding Text (only 1 chunks) Using nomic-embed-text:latest (or Naive)

### ISSUE THREAD

**Issue by Kias-llm** [Mintplex-Labs/anything-llm#2330]
### How are you running AnythingLLM?

Docker (local)

### What happened?

anythingllm         | [backend] info: [DocumentManager] Found 1 pinned sources - prepending to content with ~14426 tokens of content.
ollama              | [GIN] 2024/09/20 - 01:14:44 | 200 |      23.585µs |   192.168.176.1 | HEAD     "/"
anythingllm         | [backend] info: [OllamaEmbedder] **Embedding 1 chunks of text with nomic-embed-text:latest**.
ollama              | [GIN] 2024/09/20 - 01:14:44 | 200 |  107.954705ms |   192.168.176.1 | POST     "/api/embeddings"
anythingllm         | [backend] info: LanceDB: A source was filtered from context as it's parent document is pinned.
anythingllm         | [backend] info: LanceDB: A source was filtered from context as it's parent document is pinned.
anythingllm         | [backend] info: LanceDB: A source was filtered from context as it's parent document is pinned.
anythingllm         | [backend] info: LanceDB: A source was filtered from context as it's parent document is pinned.
anythingllm         | [backend] info: [fillSourceWindow] Need to backfill 4 chunks to fill in the source window for RAG!
anythingllm         | [backend] info: Cannonball results 14439 -> 930 tokens.
ollama              | [GIN] 2024/09/20 - 01:15:00 | 200 | 14.900320052s |   192.168.176.1 | POST     "/api/chat"
-------------------------------------------------------------------------------------------------
There is an issue with the embedding process when using nomic-embed-text:latest. According to the logs, 6-7 chunks of text are being created, but only 1 chunk is successfully embedded. This may lead to potential data loss, as not all chunks are being processed as expected. Additionally, there is no mention in the logs of any configuration settings that might explain or resolve the issue.

P.S.: Thank you for creating such a great application!

**Comment by timothycarambat** [comment]
> According to the logs, 6-7 chunks of text are being created, but only 1 chunk is successfully embedded.

I am not seeing this in the log attached. This looks to be a log that is produced when sending a chat, which 1 chunk would make sense (since it depends on the length of the prompt) and is used for similarity search.

Which then seems to return some results which are _then_ filtered out because your pinned document must contain them and is highjacking the entire context window since you want the whole document in the chat - but your Ollama window is not large enough so we have to truncate.

From the logs above, nothing glaringly wrong with the embedder, but I would unpin your document since its being truncated due to your limited context window using Ollama
