### ISSUE TITLE
[BUG]: LMStudioEmbedder try to fetch with HEAD an incorrect end-point

### ISSUE THREAD

**Issue by predoctech** [Mintplex-Labs/anything-llm#2333]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When using LMStudio as embedder, a call to LMStudio resulted in 
> [ERROR] Unexpected endpoint or method. (HEAD /v1/embeddings/models).  Returning 200 anyway

In the code "this.basePath" has been updated as "${process.env.EMBEDDING_BASE_PATH}/embeddings" in the class constructor.   Thus "this.basePath/models" would contain the values as in the error message.  The correct endpoint is "/v1/models"

### Are there known steps to reproduce?

1. Set LMStudio as Embedding Provider in Embedder
2. Upload a document and move it to Workspace
3. "Save and Embed" should trigger the call to LMStudio
4. Error message show up in LMStudio Server log

**Comment by timothycarambat** [comment]
This is not a bug, it is just set up incorrectly if I am understanding correctly. The LMStudio base path is _always_ 
`HTTP(s)://your-ip-or-host:port/v1`. Just because it is used for the embedder does not mean to pre-empt the URL with `HTTP(s)://your-ip-or-host:port/v1/embeddings` or else the above bug will indeed produce

**Comment by migueloporto** [comment]
Hello, sorry for reopening this topic. I’m experiencing the same problem. My base path is `HTTP(s)://your-ip-or-host/v1`. The issue is that the endpoint in my LM studio is `/v1/embeddings`, but anything makes a POST request adding a `/models` to the path, causing the error [ERROR] Unexpected endpoint or method. (HEAD /v1/embeddings/models). Returning 200 anyway.


https://github.com/user-attachments/assets/bc756978-2b1d-4b78-98b5-d481fe60d102

**Comment by timothycarambat** [comment]
@shatfield4  ^

**Comment by Br0wn1e23** [comment]
Jup, same problem is occuring for me.

**Comment by ibetho** [comment]
same issue :(

**Comment by softyoda** [comment]
> This is not a bug, it is just set up incorrectly if I am understanding correctly. The LMStudio base path is _always_ `HTTP(s)://your-ip-or-host:port/v1`. Just because it is used for the embedder does not mean to pre-empt the URL with `HTTP(s)://your-ip-or-host:port/v1/embeddings` or else the above bug will indeed produce

It would be nice to have the copy button near the text field "Reachable at:" to have this /v1 in the url
