### ISSUE TITLE
[BUG]: LMStudioEmbedder still cannot embed a user chat from AnythingLLM

### ISSUE THREAD

**Issue by predoctech** [Mintplex-Labs/anything-llm#2339]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Still run into error message in both AnythingLLM desktop app as well as LMStudio server . Detailed screenshot:
AnythingLLM:
![Screenshot 2024-09-21 112212](https://github.com/user-attachments/assets/1581e2f4-c5ed-4455-8bca-c34294f88385)
LMStudio:
![Screenshot 2024-09-21 112348](https://github.com/user-attachments/assets/b655bc61-2037-46de-b13b-21550a69906a)
Just using the default config to connect to LMStudio but in case that is where the issue is:
![Screenshot 2024-09-21 112532](https://github.com/user-attachments/assets/5aa4438c-6a2a-427b-acfc-56fba6c9cb31)

So really not sure where things have gone wrong.  That is the right set up as far as I can tell.  Please help.  Thanks.

### Are there known steps to reproduce?

AnythingLLM: Desktop v1.6.7 (Windows)
LMStudio: 0.3.2 (Windows)
Embedding model: https://huggingface.co/second-state/E5-Mistral-7B-Instruct-Embedding-GGUF

**Comment by timothycarambat** [comment]
Likely overflows because if you have a lot of text your current window is set to 8192

Embedding model card says:
> Context size: 4096


So you set the window to double the size which means if you have a lot of document text it will permit double the amount of text to embed is can handle - thus aborting and returning nothing
