### ISSUE TITLE
Undesirable Responses with Custom Prompts in AnythingLLM using OpenAI.

### ISSUE THREAD

**Issue by KavAndritz** [Mintplex-Labs/anything-llm#2369]
### How are you running AnythingLLM?

Local development

### What happened?

Current Behaviour:
When setting custom prompts in the chat settings of AnythingLLM, I have configured the agent to respond with "Out of scope" for questions that are not relevant to the database. However, the agent is incorrectly responding with "Out of scope" to all questions, regardless of their relevance to the database.

Expected Behavior:
The agent should only respond with "Out of scope" when the question is genuinely unrelated to the database. For relevant questions, the agent should provide appropriate responses based on the database content.

### Are there known steps to reproduce?

• **Set Up the Database:**
     Configure the database in AnythingLLM using the OpenAI GPT-4 model. Issue also tested with GPT-4o, GPT-4-mini, and 
       GPT-4-turbo.
• **Customize Chat Settings:**
      Set custom prompts in the chat settings. Tested with 4-5 different prompt variations.
• **Test the Agent:**
	Ask the agent both relevant and irrelevant questions related to the use case (presses). The agent responds with "Out of 
         scope" for all questions, regardless of relevance.

**Comment by tranmh** [comment]
Hi!

Why was it labled from "possible bug" to "question". Did you reproduce the bug already and are saying "work-as-designed"? 

Thx.

**Comment by timothycarambat** [comment]
Because this is not a bug in the software sense. You labeled this as a bug, but it's just how you set up the system and are using it to seemingly do something it probably is not explicitly designed to do but the issue is not really clear to me what the intentions are.

> Ask the agent both relevant and irrelevant questions related to the use case (presses). The agent responds with "Out of
scope" for all questions, regardless of relevance.

this is basically a use case that is not working for you. There is not bug or feature request here to action on in the software sense. if a model does not work the way you want it is on the _model side_ and could be a hallucination, refusal, or otherwise and there is not amount of code to write to make a model behave in a strict way.

You are using agent to basically refuse a query based on what is in a database (using the SQL connector?) but how can it know what is in the DB in advance without querying it? 

This is a use-case/config/setup issue
