### ISSUE TITLE
[FEAT]: More user and API customization

### ISSUE THREAD

**Issue by jayteaftw** [Mintplex-Labs/anything-llm#2372]
### What would you like to see?

I was looking into using anything-llm as it seems to have a suite of features.
However, I was curious if better User authentication could be implemented (or already exists)
The two things I am looking for are 
1) Custom external login/signup auth flow.
When a users attempts to signin, they are sent to an external web auth (in my case I am using a CAS system) and when redirected anythingLLM would look into the JSON response which contains a JWT token that has fields that could be customized

2)
API calls being made can have custom headers attached, Our custom LLM solution utilizes the JWT token mentioned before to see if an API call is authorized so being able to pass it through any of the API calls would be ideal instead of using an API token

Note: I am a Python user with little JS experience but would be willing to help if this is something the platform could be able to support

**Comment by timothycarambat** [comment]
We are building external auth plugins where you could assign a flow like this (probably via popup and parent.postMessage listening) which will also be how SSO #1193 will function. 

Track that issue for implementation since that will be how to do this since out of the box, this specification is too niche to put in the main app. It will function a lot like agent skill plugins!
