### ISSUE TITLE
[BUG]: Docker container locks up and becomes unhealthy after uploading document

### ISSUE THREAD

**Issue by mortenfj** [Mintplex-Labs/anything-llm#2421]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

**Description:**

I encountered an issue while using the AnythingLLM Docker container. After creating a workspace and uploading a small document, the platform locks up and eventually the container goes to "unhealthy" status.

Steps to reproduce:
1. Spin up the AnythingLLM Docker container.
2. Create a user account and a workspace (named "test" in my case).
3. Upload a small document (e.g., a 2k .md file).
4. Add the document to the workspace.

**Expected behavior:**
The document should be successfully added to the workspace, and the platform should continue functioning as normal.

**Actual behavior:**
After uploading and attempting to add the document to the workspace, the platform locks up and becomes unresponsive. Eventually, the Docker container goes into an "unhealthy" state. 

**Container logs:**
```log
[backend] info: [TELEMETRY SENT] {"event":"document_uploaded","distinctId":"9093e490-272d-4ef4-bae4-994906775c0b","properties":{"runtime":"docker"}}
[backend] info: [Event Logged] - document_uploaded
[backend] info: [TELEMETRY SENT] {"event":"workspace_thread_created","distinctId":"9093e490-272d-4ef4-bae4-994906775c0b::1","properties":{"multiUserMode":true,"LLMSelection":"generic-openai","Embedder":"native","VectorDbSelection":"lancedb","TTSSelection":"native","runtime":"docker"}}
[backend] info: [Event Logged] - workspace_thread_created
[backend] info: Adding new vectorized document into namespace test
[backend] info: [NativeEmbedder] Initialized
[backend] info: [RecursiveSplitter] Will split with {"chunkSize":1000,"chunkOverlap":20}
[backend] info: Chunks created from document: 1
Error: Failed to load model because protobuf parsing failed.
    at new OnnxruntimeSessionHandler (/app/server/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at /app/server/node_modules/onnxruntime-node/dist/backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback.
[backend] info: [NativeEmbedder] Failed to download model from primary URL. Using fallback https://s3.us-west-1.amazonaws.com/public.useanything.com/support/models/
Error: Failed to load model because protobuf parsing failed.
    at new OnnxruntimeSessionHandler (/app/server/node_modules/onnxruntime-node/dist/backend.js:27:92)
    at /app/server/node_modules/onnxruntime-node/dist/backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback.
```

**Environment:**
- Docker runtime
- Workspace: multiUserMode = true
- Vector DB: LanceDB
- Embedder: NativeEmbedder

**Additional information:**
The issue seems to stem from an error in loading the ONNX model, where protobuf parsing fails, forcing a fallback to a WebAssembly (WASM) implementation. Despite this fallback, the platform becomes unresponsive, and the container becomes unhealthy.

**Comment by timothycarambat** [comment]
This is because the local embedding model could not be downloaded - we first try to download from HF, then fallback to a bucket we duplicated the information to because of VPN issues from HF.

This model _only downloads on its first use_ and is reused from then on. If the model cannot be streamed or downloaded then the embedding will always fail.

Are you offline or on a restricted corporate network? You should see a `Xenova` folder in your AnythingLLM container storage/models/ folder.

**Comment by kmccullor** [comment]
I ran into a similar issue trying to upload the first document.

anythingllm  | Error: Failed to load model because protobuf parsing failed.
anythingllm  |     at new OnnxruntimeSessionHandler (/app/server/node_modules/onnxruntime-node/dist/backend.js:27:92)
anythingllm  |     at /app/server/node_modules/onnxruntime-node/dist/backend.js:64:29
anythingllm  |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
anythingllm  | Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback. 
anythingllm  | [backend] info: Caching vectorized results of custom-documents/RNI-4.14.1-Release-Notes.pdf-c2895696-947d-43a6-b6eb-84f86f52c179.json to pr

**Comment by timothycarambat** [comment]
@kmccullor Failed to download local embedder model (for any reason)
https://github.com/Mintplex-Labs/anything-llm/issues/3031
