### ISSUE TITLE
[BUG]: 不能连接网络，运行AI Agents无效

### ISSUE THREAD

**Issue by xvshi** [Mintplex-Labs/anything-llm#2429]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

开启管理员指令中的网络链接模式后，AI Agents配置也正常，但是对话无法正常使用，无法访问网络
![2fe67692-9a5f-46cd-b7c1-7b1c21a4806d](https://github.com/user-attachments/assets/79f00818-52f6-4593-8df7-7fdf426c2325)
![78b26647-28fc-4f7d-ab6d-cb7fb5cac7b7](https://github.com/user-attachments/assets/152c2403-417b-4cda-a447-fd5c6d113bed)
![aa6280d1-9e57-496f-b856-9c646f6a3cbf](https://github.com/user-attachments/assets/e9adf1cb-c161-46eb-b8ba-6fc208bee3f9)

**Comment by timothycarambat** [comment]
> [Translated] After turning on the network link mode in the administrator command, the AI ​​Agents configuration is normal, but the dialogue cannot be used normally and the network cannot be accessed.

With your prompt, you seem to have called `@agent` but **it did not start a session**. Is there any empty space at the start of that prompt or something?

You know `@agent` is working because you would see this right at the start under your first agent prompt
<img width="832" alt="Screenshot 2024-10-07 at 10 52 43 AM" src="https://github.com/user-attachments/assets/b9798c31-2e9c-46d6-8ea1-57d9b9acdf7b">

**Comment by timothycarambat** [comment]
Additionally, the Network sharing mode is _only to allow external devices to reach your desktop's AnythingLLM instance_. It has no impact on agent or tool calls and unless you are using the Developer API for other devices to use your AnythingLLM instance on your desktop - you should turn it off
