### ISSUE TITLE
[BUG]: Github connector references to master when the branch main is selected.

### ISSUE THREAD

**Issue by jhmz333** [Mintplex-Labs/anything-llm#2434]
### How are you running AnythingLLM?

Docker (local)

### What happened?

The github connector doesn't use the branch selected when the branch is **main**.

### Are there known steps to reproduce?

I'm trying to scrap the documentation of Kong API Gateway from their github repository, and I have seleted the main branch:
![Github connector failed](https://github.com/user-attachments/assets/d4f87b12-e3b5-46c2-a9bb-6994da865174)

But Anything try to get data using the master branch as a reference:
![Anything logs](https://github.com/user-attachments/assets/607c5777-dcf3-461b-95ff-36f2c8cc5505)

**Comment by timothycarambat** [comment]
@jhmz333 To avoid this issue, just post in the real repo origin and not a link to a file directly on the tree.
So in your example: `https://github.com/Kong/docs.konghq.com`

**Comment by jhmz333** [comment]
> @jhmz333 To avoid this issue, just post in the real repo origin and not a link to a file directly on the tree. So in your example: `https://github.com/Kong/docs.konghq.com`

Hi @timothycarambat, thanks for the suggestion, however, I just need a part of the repo, for that reason, I used the link to a folder directly on the tree, I wanted to avoid loading the entire repo.

**Comment by timothycarambat** [comment]
Ah, I see - in that case you can use the `file ignores` section and use it like a gitignore where you can ignore all and then `!` what you are looking for. The default (and typical behavior) is to pull in everything. 

I can see the use for only pulling specific files though since most repos may not 100% useful - in which case scraping their github.com/raw URL using the regular website scraper might be better - of course if it is a private repo then you need to just copy paste or something :/
