### ISSUE TITLE
How to upgrade a docker installation to the latest version

### ISSUE THREAD

**Issue by jignnsd** [Mintplex-Labs/anything-llm#248]
Please help!
I did a anything-llm docker installation in multi-user mode, I want to upgrade the latest version. It is installed on my server that is exposed to the internet with its own public domain. How is the best way to do it without loosing workspaces data, users, etc? many thanks

**Comment by timothycarambat** [comment]
Since you are in docker mode - you should be able to `Export` from the UI settings and obtain a `.zip` file of your entire AnythingLLM data.

Then you can update + rebuild and load in the same `.zip` file and it should restore your data. Once you upload the new zip you should also go to the `/api/migrate` endpoint to make sure the database schema is correct.

**Comment by jignnsd** [comment]
Many thanks @timothycarambat for your quick response. I'll be checking this. Take care
