### ISSUE TITLE
[API] Chat with a workspace via API endpoint

### ISSUE THREAD

**Issue by jignnsd** [Mintplex-Labs/anything-llm#249]
Hi! I want to use the developer API to ask questions to a specific workspace data. Is this possible? If yes, how? If not, is this in the roadmap? This is a very helpful tool request in order to make some automations that require answers from our own data.
Many thanks for the support.

**Comment by timothycarambat** [comment]
When running the application locally, on docker, or otherwise you can visit the backend API URL `/docs` and you will see then known endpoints. However, currently, it looks like there is no way to run a chat against a workspace.

We should have the ability to execute a new workspace chat from the API 👍

**Comment by jignnsd** [comment]
Many thanks for the time you took to answer @timothycarambat i look forward for this improvement!
