### ISSUE TITLE
[Question] Knowledge Base: Automatic File Sync in Workspace

### ISSUE THREAD

**Issue by spyroskotsakis** [Mintplex-Labs/anything-llm#2522]
Hi there!

I hope this isn't a repeat question, but I couldn't find anything related in the issues. I'm wondering if it's possible to automatically sync a folder with documents in a workspace in the Docker version. Ideally, I'd like new files to be automatically embedded and available in the workspace without needing to add them manually. 

I’ve checked through the Documentation but it seems like new files have to be added manually. Is there an option to enable automatic syncing that I might have missed?

Thanks so much for your help!  
Spyros

**Comment by timothycarambat** [comment]
Due to browser permissions automatically syncing local files is not possible/supported since the browser would need continuous access to your file system. Only the desktop app can continuously sync local files as they change.

The docker image can only sync remote data sources (websites, github, etc)
https://docs.anythingllm.com/beta-preview/active-features/live-document-sync
