### ISSUE TITLE
Multi users are able to see all the documents from other users

### ISSUE THREAD

**Issue by MirzaAreebBaig** [Mintplex-Labs/anything-llm#253]
Hello,
I have enabled multi user but all the users are able to see documents uploaded from other users as well which doesn't work well for other user as the new users creates a workspace to see, embed & chat with only their uploaded documents.

**Comment by TychoML** [comment]
Just to be sure, but those other users, are they regular users or admins? In the latter case, that would be the expected behaviour.

**Comment by MirzaAreebBaig** [comment]
Hey,
Other users are regular users. I have a admin user & 2 users as member user1 & user2.
What is uploaded by admin is visible to user1 and user2.
What is uploaded by user1 is also visible to user2, admin & vice versa.
So if all users are able to see all documents it will create confusion for everyone as the user might have to go through a bunch unnecessary items which isn't uploaded by them.

**Comment by TychoML** [comment]
Ok I get it now, I have that behaviour too. Meaning, in the current setup of a-llm all users can see all uploaded files, from which you can then freely choose which ones to include in a workspace. The confusion then potentially stems from the fact that you can only upload files from within a workspace, instead of outside of it. Personally I do not mind that uploaded documents can be viewed by others, but then if would be good if the two were distinct, meaning that you would have a separate Upload documents button in the main page of the UI.

**Comment by MirzaAreebBaig** [comment]
Yes it would be great if every user as "member" uploading files should not be visible to others because sometimes if files are more then for users to select documents in workspace will become a time taking process so if the user is just be able to see there own documents then it would reduce their time to select it in the workspace as well.

**Comment by TychoML** [comment]
I think it is done from the perspective of not incurring additional cost (vectorizing the same document twice). Still, I agree that there is room for improvement. For instance, an option to delete uploaded files, and having the ability to have multiple upload folders (now it is one big custom documents folder for me). @timothycarambat perhaps you can express your view on the question from @MirzaAreebBaig if you have time?

**Comment by timothycarambat** [comment]
Right now all members can view all files. Some things that are coming that might make more sense in context:
- Total UI overhaul and change (includes the file selector and deleting files, folders and making new folders)
- New role that is "chat only" and cannot even open the workspace settings

Yes originally showcasing all the files was more of a "Cooperative" model where that would be okay and people would not upload and pay to re-embed documents.

It appears that multi-tenet agencies have moved more towards "I will control docs and workspaces and let you use them". We weren't sure which management style would be used at first so we made an assumption there.

**Comment by TychoML** [comment]
@timothycarambat  Thank you for the kind answer, and great to hear about the upcoming features! Looking forward to it!

**Comment by MirzaAreebBaig** [comment]
@timothycarambat Thank you for your attention over this matter i suppose the things you have mentioned will solve the problem. Do we have any kind of roadmap to follow the upcoming features & can submit new features with information?

**Comment by timothycarambat** [comment]
Resolved by https://github.com/Mintplex-Labs/anything-llm/pull/351

**Comment by dlaliberte** [comment]
> Yes it would be great if every user as "member" uploading files should not be visible to others because sometimes if files are more then for users to select documents in workspace will become a time taking process so if the user is just be able to see there own documents then it would reduce their time to select it in the workspace as well.

As administrator, I am still bothered by seeing every individual file that was added (by myself, in this case) to My Documents for one of my workspaces. I have to wade through the list to find the few additional files I want to add to another workspace.

It would help a lot to organize the My Documents by folder.  In fact, related to this, it would help a lot to be able to add a whole folder/directory from my local filesystem, recursively applied to subfolders as well, rather than have to add a flat collection of files that all end up in one folder.
