### ISSUE TITLE
[FEAT]: Is there a plan to support graphrag?

### ISSUE THREAD

**Issue by SuperDuckGOGOGO** [Mintplex-Labs/anything-llm#2542]
### What would you like to see?

#1952 
#1008 
There was no answer in the link

**Comment by timothycarambat** [comment]
It is a low priority as its benefits are not across the board an improvement and come at the cost of much higher latency and costs as each query must be transformed into graph queries as well as each snippet needs to be categorized, embedded, and then upserted into a graph. While this might be tolerable for cloud LLMs, for local LLMs the latency would be very bad - which ultimately ends up with GitHub tickets saying AnythingLLM is slow, when it's just an expensive operation.

Those two issues are where they are tracked, nobody is assigned to them since the yield of this effort would benefit an extremely small amount of people, if beneficial at all.
