### ISSUE TITLE
Summarize larger documents: PIN oder Summarize Document Agent?

### ISSUE THREAD

**Issue by joomgallerytestit** [Mintplex-Labs/anything-llm#2565]
Hi,

suppose I have a PDF with 100 pages that I want to summarize.  

What would be the best approach with AnythingLLM? 

Pinning such a 100 pages document certainly requires that an LLM with a very large context window is used. 

Does a Summarize-Document Agent do anything else? 
Or do I always need an LLM with a context window the size of the document to be summarized?

Kind regards
JGallerytestit

**Comment by shatfield4** [comment]
The summarize document agent would work for you if you just need a generic overview of the entire PDF. It uses langchain's `map_reduce` summarization tool to accomplish this.

Pinning a PDF with 100 pages could also work and does require an LLM with a large context window. This would most likely cause overflow of most models and you may still lose context due to this but the result would be more detailed than the summarize document agent.

In general I would first try using the summarize document agent first then if it does not provide enough info then I would try pinning the PDF and see if it gives better results.

NOTE: The LLM may hallucinate and respond confidently incorrectly so be sure to double check it's answers as you do this because this is just the nature of LLMs (out of our control)
