### ISSUE TITLE
[FEAT]: PGVector as a Vector store

### ISSUE THREAD

**Issue by Stono** [Mintplex-Labs/anything-llm#2571]
### What would you like to see?

It'd be great to be able to use PGVector as a vector store, this would make it really trivial to host HA vector stores both locally and on many cloud providers.

**Comment by timothycarambat** [comment]
This is https://github.com/Mintplex-Labs/anything-llm/issues/873, its been talked about but becomes a big cumbersome since we need everyone to use the same schema for vector storage or require them to config it - which is rife with errors.

If we have full PG support, then PGVector makes perfect sense as well since we could handle both in one DB interface
