### ISSUE TITLE
[FEAT]: add a bulk pin feature to select multiple documents at once

### ISSUE THREAD

**Issue by xianghappy** [Mintplex-Labs/anything-llm#2586]
### What would you like to see?

"Can you add a bulk pin feature to select multiple documents at once?"
![1730778262831](https://github.com/user-attachments/assets/acde42e1-ec09-4b2b-a07a-c1125f107e86)

**Comment by timothycarambat** [comment]
This is being marked as `wontfix` as this is _intentional_. Document pinning is very helpful since it does _full document comprehension_. However, Document pinning is also a horrible idea for a large number of documents one or all of the following will occur:

- Your model context size is not big enough for all of the full documents, so they get truncated anyway so the chat completion can complete at least - omitting documents anyway.

- Your model context can fit the documents, but you are burning so many tokens forcing so many useless tokens into the context - resulting in longer inference times and higher costs (if applicable)

- This defeats the purpose of RAG, making citations extraneous if you pin everything. This makes know what citations were used nearly impossible.


Simply, document pinning is a solution for some use-cases, which is why it is supported since it can be very handy, but something is wrong if you are trying to pin every document - so the UX is to make it deliberate to discourage this
