### ISSUE TITLE
[DOCS]: Explain where chat histories are stored

### ISSUE THREAD

**Issue by c-hoffmann** [Mintplex-Labs/anything-llm#2606]
### Description

I tried finding out where AnythingLLM stores its chat histories, but didn't find in the docs. Could you please enhance the docs (and perhaps tell me here, whether the histories are stored in the browser cache (localStorage), in files on the AnythingLLM-Server..?)

**Comment by timothycarambat** [comment]
Sidebar > Workspace Chats
All the chats in raw format are storedin the associated local SQLiteDB. 

This does not have docs because we have a UI to show it and if you run in docker you know where the storage folder is since it must be set, and as a desktop app it is under the /appdata/local where other programs store data
We even have a doc page for that https://docs.anythingllm.com/installation-desktop/storage
