### ISSUE TITLE
[BUG]: Linux Installer not resolving

### ISSUE THREAD

**Issue by SammieH21** [Mintplex-Labs/anything-llm#2637]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

The following document describes how to download the app image for anything llm for linux:

https://docs.anythingllm.com/installation-desktop/linux

The Amazon AWS host for the installer and app image hasn't been resolving for the past few months as far as I'm aware:

```{bash}
curl -fsSL https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/installer.sh | sh
```
Result:
curl: (6) Could not resolve host: s3.us-west-1.amazonaws.com

**Comment by Mec-iS** [comment]
this worked for me at current time

**Comment by timothycarambat** [comment]
It is part of every deployment. If it is not resolving for you, you may be blocked by AWS/s3 due to internet restrictions or VPN restrictions - neither of which we can control since the bucket is fully public to any accessible IP.

If you cant pull the script you probably cannot pull the AppImage either.
Here is the script:
https://github.com/Mintplex-Labs/anything-llm/blob/desktop/linux_installer.sh
