### ISSUE TITLE
[FEAT]: Use ChatGPT Web Session

### ISSUE THREAD

**Issue by gmmedia** [Mintplex-Labs/anything-llm#2646]
### What would you like to see?

Would it be possible to use the ChatGPT web session as LMM?

I know this feature from some Chrome extensions. It is a big money safer for ChatGPT Plus subscribers.

**Comment by timothycarambat** [comment]
Like being able to bring your token from the `chatgpt.com` website and use it in AnythingLLM? This is not possible due to CORS. The reason this works in a Chrome extension is because the extension is basically "inside" the webpage so CORS is not a problem since the token origin is a valid OpenAI `Host`, whereas trying to use the browser token in a third party would violate this and would be blocked by OpenAI.

It is also against ToS to use the web app like that so could land users in a spot of trouble as well
