### ISSUE TITLE
[BUG]: Can‘t use speech-to-text

### ISSUE THREAD

**Issue by Kurasa632** [Mintplex-Labs/anything-llm#2651]
### How are you running AnythingLLM?

Docker (local)

### What happened?

When I use STT for input.The error is shown in the figure below.
![企业微信截图_17320057285826](https://github.com/user-attachments/assets/4baba129-66bb-4858-a6d8-e0de8892f386)

**Comment by timothycarambat** [comment]
You are either offline or cannot download the model from HuggingFace (which is where it comes from). When you use STT for the first time it streams and stores the ONNX of whisper-tiny so you can use it. It is not pre-loaded into the application since not everyone uses it.

If you have internet connectivity issues or are prevented from reaching hf.co/** endpoints (by ISP or VPN) will result in this issue. We do not mirror this model to a fallback URL, so its HF or nothing

**Comment by Kurasa632** [comment]
When I use Speech-to-text as input，the following error message is displayed:“Could not locate file:
"http://localhost:3001/static/stt/models/Xenova/whisper-tiny/tokenizer config.json”
Do you have any experience with this situation?

**Comment by qiqi0308** [comment]
in volume

**Comment by Kurasa632** [comment]
> in volume

Does the desktop support STT (Speech - to - Text)?

**Comment by qiqi0308** [comment]
> > in volume
> 
> Does the desktop support STT (Speech - to - Text)?

I use with docker,I don't konw

**Comment by shengyu27** [comment]
I have the same problem. Can anything help? Or does anyone have any solutions?
