### ISSUE TITLE
Define temperature as environment variable

### ISSUE THREAD

**Issue by jwaltz** [Mintplex-Labs/anything-llm#27]
Would it be a reasonable feature to allow temperature to be a user-defined environment variable instead of hardcoded as 0.7? I ask because when using the app as an internal knowledgebase I think a lower value or even a temperature of 0 would be beneficial.

I'd be happy to create a PR for this.

**Comment by timothycarambat** [comment]
I like this a lot, maybe as a workspace setting so its defined per workspace
- Click on the settings icon, tab for workspace config
- Temperature as setting
- Push all settings into a column on the workspaces table as stringified JSON. This is tricky because if someone pulls in changes and has a table we need a way to do a migration for the new column if not found. Even if its a special API endpoint the user can invoke to migrate all tables to the expected table format.
- The just read that in when calling `query`. Would be a huge QOL update.

**or**
We make ENV variable and if not set just falls back to 0.7 🤷 

Thoughts?

**Comment by jwaltz** [comment]
That is an excellent idea. I can see the value in configuring temperature on a per-workspace basis. Maybe a combination of both, so that a user can define a default temperature as a fallback?
