### ISSUE TITLE
How to send system prompt only at the START of a chat session?

### ISSUE THREAD

**Issue by joomgallerytestit** [Mintplex-Labs/anything-llm#2721]
Hi,

how can I prevent AnythingLLM from sending the system prompt to LM Studio **for every question within a chat session**, instead of just at the start of a chat session?

Thanks in advance
Jommgallerytestit

**Comment by timothycarambat** [comment]
You cant optionally only send it at the start. its the system prompt - it is in each request because LLMs are stateless so you need to send the whole conversation each time and the system prompts helps guide the response. 

If you want something to only be sent once in the request, then just send it as a regular chat as it will eventually be filtered out of the context window.
