### ISSUE TITLE
[FEAT]: Windows Desktop Install Web UI

### ISSUE THREAD

**Issue by quadcom** [Mintplex-Labs/anything-llm#2744]
### What would you like to see?

_** Crosposted from DIscord_

I've installed the Windows Desktop version of A-LLM and while I understand there is a team install option, in my network, it's my desktop that has a 4090. It would be a super time saver and an awesome addition if there was a way to enable a web-based UI that others on my LAN could access to use A-LLM and my GPU resources. Yes, there is Docker, but getting Docker up and running (on Win) while passing the GPU in, has proven to be challenging on the Windows platform. There's also no way that I can get ANOTHER 4090 for a Linux LLM box; I'd love to but it's not in the cards.

**Comment by timothycarambat** [comment]
You cannot just run the windows docker command?
```
$env:STORAGE_LOCATION="$HOME\Documents\anythingllm"; `
If(!(Test-Path $env:STORAGE_LOCATION)) {New-Item $env:STORAGE_LOCATION -ItemType Directory}; `
If(!(Test-Path "$env:STORAGE_LOCATION\.env")) {New-Item "$env:STORAGE_LOCATION\.env" -ItemType File}; `
docker run -d -p 3001:3001 `
--cap-add SYS_ADMIN `
-v "$env:STORAGE_LOCATION`:/app/server/storage" `
-v "$env:STORAGE_LOCATION\.env:/app/server/.env" `
-e STORAGE_DIR="/app/server/storage" `
mintplexlabs/anythingllm;
```
Then you can install Ollama on the same machine and _done_! Now you can connect AnythingLLM to Ollama and get full GPU support with the multi-user support you really want.

We wont serve the UI from the server like we do with Docker on Desktop because it will cause issues with some functionalities we have in the UI and honestly we dont want to encourage it or support it for desktop
