### ISSUE TITLE
[BUG]: Error thrown while calling application api

### ISSUE THREAD

**Issue by Vinoth414** [Mintplex-Labs/anything-llm#2761]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![image (13)](https://github.com/user-attachments/assets/db40516d-9b2f-4a63-9f7e-3ef97b58d2c5)

I encountered an error when calling the API endpoint: http://<domain>/api/ext/github/repo.

My objective is to automate the process of adding multiple repositories using this API. However, the issue arises during the execution, preventing the automation from working as intended.

Could you provide guidance on resolving this issue?

**Comment by timothycarambat** [comment]
`http:///api/ext/github/repo` is obviously not valid, what settings are you putting into the data connector field? Or, what this issue seems like is that you are trying to send a POST request directly to this endpoint without using the UI?

If you are doing the latter that isn't supported _but_ if you capture a request send via the UI you can just edit and replay it with new params each time and it will work ok
