### ISSUE TITLE
[BUG]: Cannot embed Documents on railway Docker 

### ISSUE THREAD

**Issue by KI-canvas-de** [Mintplex-Labs/anything-llm#2824]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

When I am saving a document (plain txt) to my workspace (save and embed). System responds Application failed to respond.

### Are there known steps to reproduce?

load document to workspace and save.

**Comment by timothycarambat** [comment]
Look at your railway instance, is the container starting and rebooting?

You are probably on the free tier and attempting to embed a large document using the built-in embedder. Railway free tier has _very_ limited vCPU

You should upgrade the instance so it can run the built in embedder or swap to a another provider that is off-instance so that limitation does not apply.
