### ISSUE TITLE
[DOCS]: anything-llm docker on any linux vm on promox causing bug #1331 as well!

### ISSUE THREAD

**Issue by petaehrlich** [Mintplex-Labs/anything-llm#2885]
### Description

Just spend a day and many many reinstallations on a Ubuntu 24 LTS VM with the docker anything-llm version from 1.2.0 to latest. All crashing with Illegal instruction (core dumped) node /app/server/index.js. Found out, that #1331 ist the issue in that case as well while 'mintplexlabs/anythingllm:lancedb_revert' version runs fine. Turned out that proxmox default CPU instruction set is not compatible with newer versions.

Plz add to docker documentation that proxmox (qemu in general) default CPU types for linux "x86-64-v...." are not working with newer versions of anything-llm docker. In my case the used Ryzen 7700 CPU needed "host" passthrough to get a working system.

**Comment by timothycarambat** [comment]
We don't "officially" support non-compatible CPU archs that dont have AVX2 support. I do it because I care as you found, the `lancedb-revert` tag on docker will boot, but the tag is usually way behind the current HEAD on Github because of compatibility issues.

We don't _really_ want to encourage use of that tag because it will ultimately lead us to support it fully which is more to maintain. As far as documenting it goes we can add it to the docs for sure.

Added to doc repo
