### ISSUE TITLE
[BUG]: start error

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [Mintplex-Labs/anything-llm#2890]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

after installing and louching (from installer)
it happens: 

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from
at WebContents .< anonymous> (C:\Users\Gyomei
Himejima\AppData\Local\Programs\AnythingLLM\resources\app.asar\dist-electron\m ...: 5274)
at Object.onceWrapper (node:events:628:26)
at WebContents.emit (node:events:525:35)

<img width="423" alt="image" src="https://github.com/user-attachments/assets/a6ac2489-509c-40d8-99b5-c248a63a9a9b" />

### Are there known steps to reproduce?

on windows 11 pro 24H2
download installer .exe
start installer
close installer with start anything LLM cheked
see error

**Comment by zigzagwuu** [comment]
im haveing the same issue also runing win11

**Comment by Zpowerjm** [comment]
I also encountered the same issue, and during the subsequent embedding process, it showed fetch failed

**Comment by timothycarambat** [comment]
#2710 - this does not impact using the app + @Zpowerjm your issue is unrelated and has to do with your embedder selection.

If using the native built in - your ISP/VPN is block download of the ONNX embedding model from being pulled on its first load
https://github.com/Mintplex-Labs/anything-llm/blob/dca27e7235451da9423d38976fa37aec417dda3c/server/utils/EmbeddingEngines/native/index.js#L11

If not, its whatever connection information you put for your embedder
