### ISSUE TITLE
[FEAT]: Implement advanced RAG capabilities like Lightrag or RAG 2.0 

### ISSUE THREAD

**Issue by plasi7** [Mintplex-Labs/anything-llm#2908]
### What would you like to see?

Would be nice to go beyond traditional RAG and enhance agent capabilities by implementing Lightrag or RAG 2.0

**Comment by spencerthayer** [comment]
My experience with LightRAG is that while the methodology seems to be promising, the code the developers released isn't really ready for production environments. [It is very buggy](https://github.com/HKUDS/LightRAG/issues).

RAG "2.0" is not open source, nor is it publicly available for testing. Every VC company makes a big announcement with a flashy demo, and then there's just a waitlist. It's been 283 days since [Contextual announced "2.0"](https://contextual.ai/introducing-rag2/), and as far as I know, there hasn't been any independent testing of their methodology.

**Comment by plasi7** [comment]
That makes sense and is consistent with our experience with LightRAG. Thanks for the clarification.

**Comment by timothycarambat** [comment]
This also applies to GraphRag, HippoRag, and the 400 other Rag augmentations that are niche or too nascent to be useful over a better or improved implementation on base RAG + a simple reranker.

**Comment by stockarea** [comment]
Can we use LightRAG as of today's date? the ecosystem there has matured quite a lot.
