### ISSUE TITLE
[BUG]: Only user and assistant roles are supported!. - (When I try to use anythingllm with lm studio)

### ISSUE THREAD

**Issue by winterchan2138** [Mintplex-Labs/anything-llm#2914]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

**I try to use  AnythingLLM with LM Studio and mistral-7b-instruct-v0.3 model**

I get this error on lm studio server console:

`2024-12-30 14:06:38 [ERROR] Only user and assistant roles are supported!. Error Data: n/a, Additional Data: n/a
`
In anythingllm i get:

```
Could not respond to message.
(no status code or body)
```

![image](https://github.com/user-attachments/assets/3ab8d563-46c7-43ec-a96e-ae2093055628)

In the inference tab i don't have any built in presets 
![image](https://github.com/user-attachments/assets/5a43fb10-5ef4-4231-b468-8a3aaf9d890f)

In code Snippet tab, over at the chat sub-tab 

![image](https://github.com/user-attachments/assets/fc1eadb1-6250-476d-852f-464dd02d8757)

I can see the problematic part, but it cannot be changed, i don't know how to find or change it at all.

How can i solve this problem?

### Are there known steps to reproduce?

1-Download Lm Studio and install mistral-7b-instruct-v0.3 
2-Run the server without any further changes
![image](https://github.com/user-attachments/assets/50dffecf-0720-4e75-b91e-08421042d494)

3-Download AnythingLLM and let it auto detect the server.
4-Create a new Workspace and try to chat.
5-You get this error: 
Could not respond to message.
(no status code or body)
![image](https://github.com/user-attachments/assets/84e88842-1d84-4d61-b804-923ff0f74d70)

**Comment by timothycarambat** [comment]
This is the LMStudio configuration issue, not anythingLLM: https://github.com/Mintplex-Labs/anything-llm/issues/2837#issuecomment-2549947359

As you have already shown you are using a template named `Mistral` but where did this template come from and what does it look like? The detail here is LMStudio automatically reformats incoming requests into the prompt, which since system does not exist, augments our requests to work with Mistral. Something appears to be wrong with the template or the template is not applying to incoming requests
