### ISSUE TITLE
[BUG]: Web Search Agent skill not returning a result

### ISSUE THREAD

**Issue by idealsceneprod** [Mintplex-Labs/anything-llm#2916]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I'm running the latest version of the Desktop App on Ubuntu 22.04 with an RTX2060. 

I set up the Web Search agent and pointed it to SEARXNG with the following API URL:
https://seek.fyi

Here is my request and subsequent response. Not sure what I'm doing wrong or if this really is a bug.

@agent search the web for the election results for the USA 2024 election

Agent @agent invoked.
Swapping over to agent chat. Type /exit to exit agent execution loop early.
[debug]: @agent is attempting to call `web-browsing` tool
@agent: Using SearXNG to search for "USA 2024 election results"
system profile picture
I’m sorry, but as a text-based AI model, I don’t have real-time capabilities or the ability to browse the internet. However, you can easily check the election results on news websites or official government websites for accurate information.

### Are there known steps to reproduce?

Set LLM as LM Studio, load dolphin-2.9.3-mistral-7b-32k

Set Agent Provider as LM studio with same model.

Set web serach skill to SearXNG at https://seek.fyi

Create a new thread and type a query instructing to do a current web search

**Comment by timothycarambat** [comment]
Not a bug. You are using a public instance of SearXNG and they have explicitly disabled `json` responses - likely to prevent abuse from bots. Run your own SearXNG with JSON formatting enabled as we will not parse the HTML directly since it is typically truncated and leads to poor results.

Example:
https://seek.fyi/search?q=AnythingLLM**&format=json**

The `format` parameter is the thing that allows this all to work. Run your on instance of SEARXNG or find one which support json responsese

**Comment by idealsceneprod** [comment]
> Not a bug. You are using a public instance of SearXNG and they have explicitly disabled `json` responses - likely to prevent abuse from bots. Run your own SearXNG with JSON formatting enabled as we will not parse the HTML directly since it is typically truncated and leads to poor results.
> 
> Example: https://seek.fyi/search?q=AnythingLLM**&format=json**
> 
> The `format` parameter is the thing that allows this all to work. Run your on instance of SEARXNG or find one which support json responsese

So, that means that I can only use SearXNG locally, correct?

**Comment by timothycarambat** [comment]
Or find a public endpoint which allows format=json as an output

**Comment by idealsceneprod** [comment]
I installed it on my raspberrypi but I'm still getting an error in AnythingLLM. Works fine via browser.

https://nextcloudpri:8888/search?q=AnythingLLM&format=json

Is that what the url should look like? I have json enabled in the settings file.

**Comment by timothycarambat** [comment]
The issue is going to be what you are using for the host - `fetch` may or may not be resolvin that host resulting in no response since the DNS wont resolve. Try the IP directly instead of that DNS alias. 

If there is an error it should be reporting it
https://github.com/Mintplex-Labs/anything-llm/blob/f8f0eb1d2f7d2d4ca4b6975d5e623e0c1abd106c/server/utils/agents/aibitat/plugins/web-browsing.js#L400
