### ISSUE TITLE
Problem to run locally with Docker

### ISSUE THREAD

**Issue by Zukanto** [Mintplex-Labs/anything-llm#317]
I got a Problem when I want to start LLMAnything locally. But after I  execute "docker-compose up -d --build" I got this Error ..

"287.5   nodejs
288.0 0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
288.0 Need to get 28.9 MB of archives.
288.0 After this operation, 188 MB of additional disk space will be used.
288.0 Err:1 https://deb.nodesource.com/node_18.x jammy/main amd64 nodejs amd64 18.17.1-deb-1nodesource1
288.0   404  Not Found [IP: 104.22.4.26 443]
288.0 E: Failed to fetch https://deb.nodesource.com/node_18.x/pool/main/n/nodejs/nodejs_18.17.1-deb-1nodesource1_amd64.deb  404  Not Found [IP: 104.22.4.26 443]
288.0 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
failed to solve: process "/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends         curl libgfortran5 python3 python3-pip tzdata netcat         libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1         libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1         libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1         libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release         xdg-utils &&     curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&     apt-get install -yq --no-install-recommends nodejs &&     curl -LO https://github.com/yarnpkg/yarn/releases/download/v1.22.19/yarn_1.22.19_all.deb         && dpkg -i yarn_1.22.19_all.deb         && rm yarn_1.22.19_all.deb &&     curl -LO https://github.com/jgm/pandoc/releases/download/3.1.3/pandoc-3.1.3-1-amd64.deb         && dpkg -i pandoc-3.1.3-1-amd64.deb         && rm pandoc-3.1.3-1-amd64.deb &&     rm -rf /var/lib/apt/lists/* /usr/share/icons &&     dpkg-reconfigure -f noninteractive tzdata &&     python3 -m pip install --no-cache-dir virtualenv" did not complete successfully: exit code: 100"

I already tried to reinstall node and update it. But can't get it to run always the same error

**Comment by timothycarambat** [comment]
nodesource deprecated the node_18 install script and we are pinned to node 18, will localize the file

**Comment by timothycarambat** [comment]
Replication:
I start docker
- ensure no existing images, volumes, network, or container for anythingLLM
- `docker system prune`

1. Run `docker-compose up -d --build` from `docker` folder.
2. `RUN DEBIAN_FRONTEND=noninteractive apt-get.....` command succeed.
I do notice that the depreciation notice for debian node 18 is present,but the installation completes regardless.
3. Container is available on localhost:3001

Given that this build error is not due to a file we maintain and the endpoint **does** still host the Debian image for Node 18 I am going to close this issue.

We either need to upgrade docker to Node 20 or self-host the debian image eventually to prevent issues going forward

**Comment by timothycarambat** [comment]
resolved by 2afe3faed87822857d3e189d08b8545d9e840e48
