### ISSUE TITLE
Collector on HTTPS site error - SSL: CERTIFICATE_VERIFY_FAILED 

### ISSUE THREAD

**Issue by Britman72** [Mintplex-Labs/anything-llm#330]
I'm trying to run Collector using the sitemap option. Passing it this site: https://pediatricassociates.com/sitemap

Error:

Traceback (most recent call last):
  File "<root path>/AnythingLLM/collector/v-env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^

`requests.exceptions.SSLError: HTTPSConnectionPool(host='pediatricassociates.com', port=443): Max retries exceeded with url: /sitemap (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))`

**Comment by timothycarambat** [comment]
This is not a bug on our end - it would indicate that the site you were requesting did not have a valid SSL certificate. So HTTPs would fail

Looks like a bad site config since while its redirecting or rewriting the URL the certificate is invalid and the script will not wait that long for a redirect.
<img width="440" alt="Screen Shot 2023-11-03 at 12 46 11 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/30a5a97b-7cdb-44e1-ab01-963b9112f6e2">

**Comment by Britman72** [comment]
Ah, good catch Tim. First time running the collector and as it happens the two sites I tested had the certificate issue.

Cheers.
