### ISSUE TITLE
Drive integration and document embedded cancellation

### ISSUE THREAD

**Issue by Mirgiacomo** [Mintplex-Labs/anything-llm#508]
Hi, is an integration with Google Drive or some other cloud planned?
For example, the idea is to be able to fish information from a repository of documents on Drive and embed them into our LLM.

Also, if I had 100 documents that I embed, is there an option to remove only 1 of them from my vector database or do I have to delete everything?

**Comment by timothycarambat** [comment]
- Google Drive support will be added, but likely not out of the box locally due to OAuth apps and permissioning with running on localhost or unknow IPs since google apps _must_ have a https domain for auth and we are not going to run a middleware service to support that because its not allowed by google ToS.

We will support it in one shape or form, likely some third party integration for ease of use, that will be addressed Q1 2024.

As far as documents, yes. From the document picker you can select a single document and remove it from a workspace and only its data will be removed.
