### ISSUE TITLE
Best LLM Experience on Github

### ISSUE THREAD

**Issue by scott-stuff** [Mintplex-Labs/anything-llm#552]
Setup is a breeze. LLMs are easily interchangeable. Embedding is automated. Great admin setup in the front end. Exactly what I've spent months looking for. Thanks for the awesome development!

**Comment by timothycarambat** [comment]
🚀 Glad to hear this! Myself, the team, and the contributors who help out here love to hear stuff like this. Going to close this (since it's not an issue) but I wanted to express our thanks for the kind words!

Feel free to join the Discord (link in Readme) or drop feature requests, bugs, etc here on GitHub.

Thank you for using AnythingLLM!
