### ISSUE TITLE
[BUG]:  Uploaded file name does not match the displayed file name after the upload

### ISSUE THREAD

**Issue by huicewang** [Mintplex-Labs/anything-llm#644]
### Description

 A problem has been identified where the uploaded file name does not match the displayed file name after the upload, as shown in the image: this causes the file to be unfindable during embedding.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/d0e74c95-d2bb-499f-ac48-0860cc85fffe)

**Comment by shatfield4** [comment]
Are you able to provide me with the pdf file you are using here? Through my testing I cannot replicate this bug.

**Comment by huicewang** [comment]
[深圳市艾比森光电股份有限公司发展战略规划纲要.pdf](https://github.com/Mintplex-Labs/anything-llm/files/14045008/default.pdf)
Please test this file to upload

**Comment by timothycarambat** [comment]
Thanks for the file! After downloading and uploading to anythingllm, i cannot replicate this error. Do you know what commit or docker image tag you are on? We fixed this issues (or very similar) a long time ago.

<img width="322" alt="Screen Shot 2024-01-24 at 4 04 46 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/d96e2954-3932-4db9-995c-3c48af562a07">

**Comment by huicewang** [comment]
I am deploying in a local Windows environment, and I have obtained the latest code.

**Comment by timothycarambat** [comment]
Using Docker? Can you tail the output of the `collector` process? It will report the parsed filename in the process logs, which can help debug what is going on.

**Comment by huicewang** [comment]
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/f36ef28d-fe0d-4be9-ac1d-e0451d224a5b)
the output of the collector is ok.
![image](https://github.com/Mintplex-Labs/anything-llm/assets/19237481/54ea8c3d-73b7-48bb-96a7-9c12bdb11dcb)
Please test this file
[接口性能-自动化测试的根基--HTTP协议.pdf](https://github.com/Mintplex-Labs/anything-llm/files/14045225/-.--HTTP.pdf)

**Comment by timothycarambat** [comment]
@huicewang This is because the data shown in the UI is parsed from the file metadata, not the file name (because they can be the same). It is highly likely the file with `a` as the name has that as the `title` of the PDF - for some reason.

Attached is metadata of the above file, you can see the title is set to the value in the UI.


<img width="393" alt="Screen Shot 2024-01-24 at 4 27 50 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/c8b1e7bf-7607-4c3f-8600-27bde3bdb5f1">

**Comment by timothycarambat** [comment]
Going to close as wontfix, because this is the intended effect!
https://github.com/Mintplex-Labs/anything-llm/blob/978cad476ad7a4732cc8260d92ba5d1e1de68645/collector/processSingleFile/convert/asPDF.js#L43

It falls back to the file name if no title is defined, however if the file metadata has it defined, we prefer to use it.
