### ISSUE TITLE
[FEAT]: Select folders for import

### ISSUE THREAD

**Issue by nconder** [Mintplex-Labs/anything-llm#674]
### What would you like to see?

Support the selection of folders during the import file process and be able to import the folder its self with feature #554

**Comment by ErroneousBosch** [comment]
If there was a way to simply point it at a host device folder and run it while leaving in place, this would become way more useful.

**Comment by FreezyExp** [comment]
Yes, GPT4ALL monitors a folder for document changes and reindexes the files.
That would be a very nice option

**Comment by ErroneousBosch** [comment]
I was referring to being able to open a folder on the host machine when hosting via a web based docker install. So say I have a volume bind in the container of `/reports`, being able to open and import or run embeddings on that directory, rather than uploading into the app's file structure, would be very handy when processing a large number of potentially large files that would not be practical to upload via the interface.

**Comment by sirion-demo** [comment]
If a folder is dragged and dropped on to the UI, it attempts to upload each file but it fails. Dragging and dropping each file from that same folder individually works correctly, so it's not an issue with the files. Please enable dragging and dropping of folders, thx.
