### ISSUE TITLE
The readme needs work to enable installation by following the instructions.

### ISSUE THREAD

**Issue by tabgab** [Mintplex-Labs/anything-llm#74]
This looks like a great project, and I am eager to get it going!

I have tried installing this on a Ubuntu running in WSL by following the instructions. 

~/anything-llm$ yarn setup  
00h00m00s 0/0: : ERROR: \[Errno 2\] No such file or directory: 'setup'

Then I tried the exact same workflow after cloning the repo on Mac, and it worked... Why?

The next hurdle was the fact, that nothing in the readme mentions that you need to install docker desktop on Mac. This may be self-explanatory to many, but I just followed the instructions, and kept getting the error that the docker daemon was nowhere to be found. Everything else was installed from the command line, so it is not as obvious as you would think, that docker desktop has to be installed first, and it is not mentioned anywhere.

Now all seems to be working after figuring that out, except that I get an error that the localhost could not send the chat. That is open in another issue.

**Comment by timothycarambat** [comment]
This is probably because of the yarn version or how you installed the `yarn` you are using. It is possible yarn will not infer `run` so you just need to `yarn run setup` and it will then explicitly run the `package.json` script `setup` command.

The readme for `HOW_TO_USE_DOCKER` does explicitly say to install docker and links to their service - so that is handled already! https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md#requirements

**Comment by jhalbrecht** [comment]
FWIW me too.

`yarn run setup` failed also
I installed yarn, nodejs, npm with apt on Debian 12 bookworm lxc

```
jeffa@allm:~/dev/anything-llm$ yarn run setup
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
jeffa@allm:~/dev/anything-llm$

jeffa@allm:~/dev/anything-llm$ yarn --version
0.32+git
jeffa@allm:~/dev/anything-llm$

jeffa@allm:~/dev/anything-llm$ node --version
v18.13.0
jeffa@allm:~/dev/anything-llm$

jeffa@allm:~/dev/anything-llm$ npm --version
9.2.0
jeffa@allm:~/dev/anything-llm$
```
