### ISSUE TITLE
[BUG]: GitHub integration ignores folders

### ISSUE THREAD

**Issue by kapral18** [Mintplex-Labs/anything-llm#781]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

When integrating with a public repo, it only fetches 1st level of files, it skips folders altogether.

**Comment by timothycarambat** [comment]
You did not provide a PAT (personal access token), most likely. This should be in a blue alert modal above the content.
If you dont have a token, Github can only get the top-level files because the recursive search will error due to rate-limiting

<img width="941" alt="Screenshot 2024-02-22 at 2 56 27 PM" src="https://github.com/Mintplex-Labs/anything-llm/assets/16845892/b3cadcb2-8bea-4220-aebc-626d4f96576e">

**Comment by kapral18** [comment]
@timothycarambat you were right. But now I have another problem it just shows error after a while without any description. Do you have a debug mode or something for desktop?

**Comment by timothycarambat** [comment]
🤯 That is a huge repo! You can debug by running the executable directly view terminal or Powershell - that will print logs directly to the cli while AnythingLLM is running.

Im imagining that many files is hitting the limits of the PAT
