### ISSUE TITLE
[FEAT]: New user role that can view, create, modify and delete (their own) workspaces

### ISSUE THREAD

**Issue by v3DJG6GL** [Mintplex-Labs/anything-llm#797]
### What would you like to see?

There are currently three user roles: _Default_, _Manger_ and _Admin_.
What I think is missing is something between _Default_ and _Manger_:
I would like to give some of my users roles where they can create, delete and modify their own workspaces - e.g. change the LLM model, LLM temperature and so on.
Currently I have to assign the _Manger_ role to my users to do this. But this role includes many more admin permissions that they should not have - such as _Can create, update and invite new users to the instance_.

**Comment by olariuromeo** [comment]
I think this is not enough, I think there must be a component that can create roles and permissions. So each admin can create an infinity of roles that he can manage as he wishes. and can assign to each role the permissions it wants. I think we all agree that each admin has different requirements for his platform.
Therefore, each field must have the possibility to be configured with different rights mixed on different roles.
Therefore, the platform must have different levels of granularity and rights that can be configured on each level up to the atomic level of the field.
Thus, fields can be grouped into groups of fields, which can also have rights that can be assigned to roles. at this level.
Then above there could be plugins or modules that can be integrated into the platform that can also have roles with assigned rights. This pirmaidal system of roles can be assigned different rights on different levels, thus an infinity of roles with different rights can be created, which could give the possibility for the platform to be used as everyone wants. Atomic level modularity is essential, but we cannot talk about such things when there is not even a registration form on the platform. There is no user or role management system. all these are created manually, they cannot be created dynamically at the moment. So I estimate that if this is desired, it will probably be possible in a few years. But I think that the best approach for this application is to have a system of defining roles and users through api, so the application can be integrated into any cms or application as a module, and users can have access from there, where they already there is a community and a user management system.

**Comment by timothycarambat** [comment]
@olariuromeo There is no Github issue for this, but atomic permissions are actually WIP. There are just many models and access points that must be presented in a comprehensible way for the average administrator. You do not have the appropriate background to frame why the system is the way it is currently, but this tool is an iteration moving towards a future state that actually _does_ align with your desires, oddly enough. These larger architectural changes are for the core team only since they involve the entire framework of the application. 

Every detail of your comment would be better expressed as a Github issue to voice your view on any specific feature or decision and what you would like to see. Why you would write the above comment and possibly think that would be helpful to the maintainers or community is very off-putting and communicates your ideas poorly. 

This project is open source and constantly evolving as the landscape changes, if you have problems or a better "vision" - you are allowed to build it if you think it is more important or we are not moving fast enough.

Best of luck. In the meantime, we will continue to build AnythingLLM from the voice of our community ✌️

**Comment by timothycarambat** [comment]
Moving to https://github.com/Mintplex-Labs/anything-llm/issues/1787
