### ISSUE TITLE
[BUG]: The chat and query buttons are missing after the latest update

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#822]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![Screenshot 2024-02-27 194305](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/fbe9c0b5-7629-4571-ae01-01c398075a80)

**Comment by timothycarambat** [comment]
They are not missing, they are now workspace settings because admins managing workspaces do not want users to be able to use the workspace in a mode that the document or use of that workspace is not intended for. Some dont want people to use the chat for general reference and instead only want questions with direct citations.
