### ISSUE TITLE
[Docs]: Docker compose has a bad image reference

### ISSUE THREAD

**Issue by damitjimii** [Mintplex-Labs/anything-llm#834]
### How are you running AnythingLLM?

Docker (local)

### What happened?

git auth error on deploying. 

compose file has image: anything-llm:latest but should be mintplexlabs/anythingllm:latest

### Are there known steps to reproduce?

docker run or docker up

**Comment by timothycarambat** [comment]
Closing this because this docker-compose is actually for development purposes and because of that we dont actually need the image tag at all. It was in there as a mistake, but this file should remain untouched as it is only used for quickly building/validating new changes in docker

Ideally should run the docker image by pulling it alone (or using your own docker-compose)
