### ISSUE TITLE
[BUG]: Error while moving the document to workspace when i click save and embed button on windows server with privilege account

### ISSUE THREAD

**Issue by amitnil-dev** [Mintplex-Labs/anything-llm#893]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Error while moving the document to workspace when i click save and embed button.

I face the issue on windows server 2019 when i upload a pdf document and move it to workspace. when i click save and embed button, it throws a error. I have privilege account, does it need any folder permission and where u store it(it works on local machine but not on windows server which has restrictions)
<img width="960" alt="anythingllm" src="https://github.com/Mintplex-Labs/anything-llm/assets/86748011/c689c510-b2ca-4346-aad5-552b9584714e">

secondly the window size in windows server doesnt render properly and i cant see close button in upload document screen.

eagerly waiting  for you reply.

### Are there known steps to reproduce?

windowserver 2019 try to upload a document and save and embed with privilege acccount. it will throw error

**Comment by amitnil-dev** [comment]
i think is the app is not able to save document to C:\Users\pxfw7p\AppData\Roaming\anythingllm-desktop\storage\vector-cache, i see this empty and probably do not have access to write files. 
I tried changing the .env file in storage folder to C:\Users\pxfw7p\storage but still dint work

**Comment by iVanology** [comment]
Same problem on my Mac too. Cannot move to files to workplace.

**Comment by martian-coder** [comment]
I think the project should allow custom folder to store documents n vectors in personal folder rather in appdata folders. As if you are in enterprise server environment permission to write file by exe will be blocked by policy.

**Comment by timothycarambat** [comment]
For some clarity, we designed the desktop app for Home/Professional - not for server because the desktop app is a single-player experience. Here, it makes more sense to use the Docker image (has multi-user, API, etc) on a server environment - because of permissions and the docker service not running as an exe which is very limited by default on Windows server.

Your error, however, likely comes from trying to download the embed model we use natively. We dont download this model unless we know you are using the native model to preserve disk space and not load in extra assets. This fetch can fail if you are on a limited IP range, using a VPN, firewall blocked, or any number of reasons HuggingFace may block your download.

See https://github.com/Mintplex-Labs/anything-llm/issues/821
