### ISSUE TITLE
[BUG]: Chat settings prompt [agent prompt] is being ignored

### ISSUE THREAD

**Issue by chrisribe** [Mintplex-Labs/anything-llm#911]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

Hello, 

Chat settings prompt is being ignored after "Update Workspace" button is clicked.
It is only correcly applied "after" /reset "clear your chat and begin a new chat" is clicked or a new thread is created.

There is no way for the user to know what prompt is being feed along with the input text.
Using local LLM Mistral-ins-7b-Q4

### Are there known steps to reproduce?

# Steps
1. Create a new Workspace
1. Go to default thread and ask:
"what is the weather ?"

1. Go to chat settings
Add this prompt to the chat settings
```
You are an AI assistant who ALWAYS starts the response with [AI START] and ends with [AI END]
```
1. Hit Update Workspace

1. Go to default thread and ask:
"what is the weather ?"

# Result
Response will not contain [AI START]  [AI END] until you reset the chat or create a new thread.

**Comment by shatfield4** [comment]
I just tried to replicate this but this is actually an issue with the model unfortunately. This typically happens to Mistral models for some reason but we would suggest you not use any models that have a quantization of less that 5. In the model you are using it has a quantization of 4 noted by the Q4 here: Mistral-ins-7b-**Q4**. 

This is happening because since the quantization is so low it ignores the system prompt and we have noticed it will actually ignore the system prompt baked into the model sometimes as well. Closing due to this being a model issue.

**Comment by timothycarambat** [comment]
@chrisribe Yeah, LLMs can be tricky - especially with quantized models since they are basically operating with less precision. The model was basically "over-indexing" on the format of the first messages and ignoring the instruction even in the system prompt and your next prompt. You dont see this in more "powerful" models because they can "reason" around it and understand what output you really are likely looking for. Since there was no conflict context when the history was empty, there was nothing to fight against the system prompt or your current query - so it worked.

Just a quirk of LLMs, especially running locally. We are all learning these things together 🚀
