### ISSUE TITLE
[BUG]: Feedback thumbs up and thumbs down does not do anything?

### ISSUE THREAD

**Issue by wallartup** [Mintplex-Labs/anything-llm#920]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I have tried thumbs up but don't see it anywhere in the UI. Should it not be present in the workspace chat? Where can I find the feedback otherwise from the thumbs up and thumbs down ?

### Are there known steps to reproduce?

Chat with workspace, get an answer. Below the answer there is a thumbs up or thumbs down icon. Click it. Where can I find this feedback ?

**Comment by timothycarambat** [comment]
It is present in the exports and has no impact on the ranking of historical chats. It was added because you can export your chats in various formats and then filter them out based on their rating to create a fine-tune.

It has been talked about having those actions then embedded into the workspace for memory improvement. We have not settled on the end state for that, so for now its just for exporting and helping people fine-tune later models

**Comment by mybaseai** [comment]
> It is present in the exports and has no impact on the ranking of historical chats. It was added because you can export your chats in various formats and then filter them out based on their rating to create a fine-tune.
> 
> It has been talked about having those actions then embedded into the workspace for memory improvement. We have not settled on the end state for that, so for now its just for exporting and helping people fine-tune later models

A lot of companies are looking for a feedback loop, I think it would make a lot of sense in adding it as part of a feedback loop when users are interacting with the solution.

**Comment by timothycarambat** [comment]
The thumbs down no longer exists since they dont "rank" a message at all to the LLM. Also you can now edit the LLM response to make the response better - so downvoting is redundant since you can error correct it.

Thumbs up is really just for those who export their chats for fine-tuning elsewhere.
