### ISSUE TITLE
An error occurred while streaming response. Failed to fetch , Windows 10

### ISSUE THREAD

**Issue by Alias4D** [Mintplex-Labs/anything-llm#946]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

hi , im using ollama to serve Open source LLM locally on http://127.0.0.1:11434
1 - installed AnythingLLM desktop on my windows & setting up for use ollama successfully 
2 - run app and upload my markdown files for embedding successfully .
3 - write my qustion on prompt ? but get this message error below
![image](https://github.com/Mintplex-Labs/anything-llm/assets/27604791/5342c85f-0529-43f5-81b2-a3f3ed456d98)

**Comment by xia0ji233** [comment]
I have same problem,but I build it locally,and server on localhost:3001 will crash after I ask two problem.

<img width="1566" height="269" alt="Image" src="https://github.com/user-attachments/assets/2e00e433-e791-4473-b38c-b66597219baa" />

**Comment by timothycarambat** [comment]
502 is a bad gateway error code - likely from your NGINX webserver config because you [did not enable websockets in the config](https://github.com/Mintplex-Labs/anything-llm/blob/master/cloud-deployments/aws/cloudformation/aws_https_instructions.md#step-7-create-simple-http-proxy-configuration-for-anythingllm)

We should update docs to have this default config on that page to stop this hiccup since its a user-config issue
