### ISSUE TITLE
List of uploaded PDFs showing every page as one file

### ISSUE THREAD

**Issue by bibi-b** [Mintplex-Labs/anything-llm#95]
First of all: Awesome project! Thanks for that!

I uploaded a PDF with plenty of pages and the dialog shows me every page as one file. That makes it impossible to select or de-select the PDF for a workspace. Or am I doing something wrong?

![Bildschirmfoto 2023-06-20 um 13 43 27](https://github.com/Mintplex-Labs/anything-llm/assets/59328072/3b591f81-c2c3-437d-a882-39fbcda85598)

**Comment by timothycarambat** [comment]
by default, the PDF is page-separated since some pages may not be desired to be embed. This is something that will be fixed in future versions where paginated documents will not be pushed into the root custom-documents and instead will be housed in it own folder.

Then you can click the root document and have all pages separated.
