### ISSUE TITLE
[FEAT]: Store source URL; Link to the source document

### ISSUE THREAD

**Issue by Tiberius1313** [Mintplex-Labs/anything-llm#965]
### What would you like to see?

After uploading a document a parsed JSON file is stored in “custom-documents”.  That file contains the information:
- "url": “file://C:\\Users\\[USER]\\AppData\\Roaming\\anythingllm-desktop\\storage\\hotdir\\[NAME_OF_THE_SOURCE_FILE.EXTENSION]"
-  "docSource": "pdf file uploaded by the user."

To my understanding this information is useless.

Would it instead be possible to store the path URL of the originally uploaded source document?
Would it also be possible to show that link in the LLM reply as a reference and also  to allow the user to open that document and  maybe even to see the refereed text highlighted?

**Comment by timothycarambat** [comment]
The reason why this data is omitted and/or useless (it's not even used in inferencing) is because 
1. It would be impossible to replicate this for hosted/self-hosted ANythingLLM. Unable to open a local file from a remote system.
2. Security implications of the above and should the file move, its reference would be broken anyway.

There is some ideas for "living" files but this would be handled in a different way for local files and would be unavailable for hosted instances regardless since the #1 point still applies.

Currently, the functionality described only works for URLS
