### ISSUE TITLE
can't access the server website

### ISSUE THREAD

**Issue by aixintiankong** [Mintplex-Labs/anything-llm#997]
### How are you running AnythingLLM?

Local development

### What happened?

after build anythingllm on linux workstation, on my windows system computer can't access the website by ip:3001. the webpage is black and spinning circle. colud help me?
<img width="966" alt="Screenshot 2024-03-30 at 15 12 23" src="https://github.com/Mintplex-Labs/anything-llm/assets/12507774/a1777102-81fd-4d56-8b2f-70b492394903">

**Comment by timothycarambat** [comment]
https://github.com/Mintplex-Labs/anything-llm/blob/master/BARE_METAL.md#run-anythingllm-in-production-without-docker

> Warning
> 
> This method of deployment is not supported by the core-team and is to be used as a reference for your deployment. You are fully responsible for securing your deployment and data in this mode. Any issues experienced from bare-metal or non-containerized deployments will be not answered or supported.

The reason for this warning is that in local development there are an unlimited amount of ways and configurations you can set things up and any one of those changes could be an issue. That is why we cant really support every ticket like this, its just too much for our team.

That being said, if you are seeing the spinner it _likely means_ that the frontend is there, but cannot talk to the backend.
1. Ensure when building the frontend that the `.env` in the frontend is set with this value
```
VITE_API_BASE='/api'
```

2. Then bundle the frontend and place in `server/public/` and the frontend should then be looking at wherever it is hosted to serve.

Above is _usually_ where things go wrong for most people building themselves. Otherwise, the Discord may be a better place to ask as there are more people there and ones with experience doing this and debugging in a less formal manner than on GitHub
