### ISSUE TITLE
[BUG]: Stop button does not stop Ollama backend

### ISSUE THREAD

**Issue by sumitsodhi88** [Mintplex-Labs/anything-llm#998]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

So when I use a stop button the inference is not reflected in the chatbox, but in the backend the Ollama is still working on the inference. Now when I ask a new question the Ollama is stil working on the old question.
The STOP button thus not implemented correctly in case of ollama. The system should send abort to the Ollama too.
![Screenshot from 2024-03-30 13-55-46](https://github.com/Mintplex-Labs/anything-llm/assets/149290101/93c7b342-99d1-4bc7-af5f-e3548c47900f)

**Comment by CharlesBdg** [comment]
This should help : https://github.com/ollama/ollama/issues/1695

**Comment by timothycarambat** [comment]
We do call abort on the response, which does exactly as that thread perscribes, so i think the issue is related to CPU inferencing ([comment](https://github.com/open-webui/open-webui/issues/1166#issuecomment-2016946749))

**Comment by timothycarambat** [comment]
Closing as it seems that the ollama thread (and other fixes like this) do not stop CPU inferencing and that seems to be tied to how llamacpp sends abort requests, which seems to only take effect with GPU inferencing

**Comment by 17Reset** [comment]
Also encountering this kind of problem, there is a situation where this must be done: when the LLM is in error and keeps returning the wrong content, this is when the stop button should be necessary, in the case of Ollama's api calls, if this kind of problem is encountered, it is possible to locally terminate the process or thread of the api call to turn off the output of the big model on the server, and then Anythingllm doesn't seem to support.

**Comment by workturnedplay** [comment]
This isn't only due to CPU inferencing, if I use a model that fits into VRAM and uses exclusively the GPU (like https://ollama.com/library/granite4.1:3b-q2_K ) it still happens (Stop doesn't cause GPU to go down from 98% usage, and model is for example stuck in a loop and keeps outputting but anythingllm doesn't show it due to Stop, but ollama keeps running it) and the only workaround to stop it is to quit AnythingLLM (ie. from systray). How about a workaround: disconnect and reconnect to ollama? like cline is doing:
> Cline does call abort() on the request when you cancel a task — this was fixed in v3.41.0. What that does is **close** Cline's **HTTP connection to Ollama**. The problem is Ollama's server doesn't stop generating when the connection drops — it queues new requests and keeps the current one running until it finishes. This is specific to Ollama's architecture; llama-server handles connection drops differently, which is why it stops cleanly.
[quote src](https://github.com/cline/cline/issues/9442#issuecomment-4182720933)

I can confirm the connection (between anythingllm and `ollama serve`) is kept `Established` (seen via TinyWall) even though `Stop` was pressed. That's why `Quit` works because it closes the connection and then `ollama serve` shows only this line when that happens:
`[GIN] 2026/05/18 - 21:33:18 | 200 |          2m8s |       127.0.0.1 | POST     "/api/chat"`

AnythingLLM v1.12.1
