### ISSUE TITLE
[BUG]: Uploading Chinese pdf files, move to workspace failed

### ISSUE THREAD

**Issue by arvinhan** [Mintplex-Labs/anything-llm#999]
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

![image](https://github.com/Mintplex-Labs/anything-llm/assets/31042264/10b41564-341c-4cfa-a443-097a780af14f)

**Comment by watsonzh** [comment]
Not only the Chinese file, upload the English file, move to the workspace still failed.
My software is configured as follows:
LLM Selection：Ollama
Embedding Engine：AnythingLLM Embedder
Vector Database：LanceDB

**Comment by timothycarambat** [comment]
It is this pinned issue: https://github.com/Mintplex-Labs/anything-llm/issues/821

If you are based in CN or using a VPN HuggingFace typically blocks the IP. We will likely eventually host the model centrally since it seems 90% or more of people use the default embedder at least once and we get this issue reported about 4 time s a week
